= Google Cloud SQL Spring Boot Starter

Maven coordinates, using Spring Cloud GCP BOM:

[source,xml]
----
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-gcp-starter-sql</artifactId>
</dependency>
----

Gradle coordinates:

[source]
----
dependencies {
    compile group: 'org.springframework.cloud', name: 'spring-cloud-gcp-starter-sql', version: '1.0.0.BUILD-SNAPSHOT'
}
----


This starter provides the configuration sources: `CloudSqlJdbcInfoProvider` and `DataSource`.

`CloudSqlJdbcInfoProvider` returns the JDBC information to be used, such as the JDBC driver name
and connection string. A special `CloudSqlJdbcInfoProvider` is provided if an app is running on
Google App Engine.

`CloudSqlJdbcInfoProvider` requires the following properties:

[source,yaml]
----
spring.cloud.gcp.sql.database-name=[YOUR_CLOUD_SQL_DATABASE_NAME]
----

The following properties are optional:

[source,yaml]
----
spring.cloud.gcp.sql.instance-connection-name=[YOUR_CLOUD_SQL_INSTANCE_CONNECTION_NAME]
spring.cloud.gcp.sql.jdbc-url=[YOUR_JDBC_URL]
spring.cloud.gcp.sql.jdbc-driver=[YOUR_JDBC_DRIVER]
spring.cloud.gcp.sql.user-name=[YOUR_CLOUD_SQL_USERNAME]
spring.cloud.gcp.sql.password=[YOUR_CLOUD_SQL_PASSWORD]
----

`spring.cloud.gcp.sql.instance-connection-name` is your instance's
https://github.com/spring-cloud/spring-cloud-gcp/tree/master/spring-cloud-gcp-starters/spring-cloud-gcp-starter-sql#google-cloud-sql-instance-connection-name[connection name].
Required if `spring.cloud.gcp.sql.jdbc-url` isn't specified.

If `spring.cloud.gcp.sql.jdbc-url` is specified, it is used as the final JDBC URL and has precedence
over `spring.cloud.gcp.sql.instance-connection-name`.

If `spring.cloud.gcp.sql.jdbc-driver` isn't specified, `com.mysql.jdbc.Driver` is used by default,
or `com.mysql.jdbc.GoogleDriver` if running on Google App Engine.

If `spring.cloud.gcp.sql.user-name` isn't specified, `root` is used by default.

If `spring.cloud.gcp.sql.password` isn't specified, an empty string is used by default.

By using this starter in conjunction with
https://docs.spring.io/spring/docs/current/spring-framework-reference/html/jdbc.html[Spring JDBC],
it's possible to inject a fully configured `JdbcTemplate` object only from adding the required
properties.

The returned `DataSource` is an implementation of
https://brettwooldridge.github.io/HikariCP/[HikariCP]. If you want to use another kind of
`DataSource`, feel free to use the provided `CloudSqlJdbcInfoProvider` to provide your own
`DataSource` bean.

=== Google Cloud SQL Instance Connection Name

A Google Cloud SQL instance connection name is a string comprised of three elements:

`[YOUR_GCP_PROJECT_ID]:[YOUR_INSTANCE_REGION]:[YOUR_INSTANCE_NAME]`

You can find your instance's connection name in its Google Cloud Console page.

== Frequently Asked Questions

=== I'm seeing a lot of log lines similar to "c.g.cloud.sql.core.SslSocketFactory : Re-throwing cached exception due to attempt to refresh instance information too soon after error." in a loop and I can't connect to my database

This is usually a symptom that something isn't right with the permissions of your credentials. For
example, your service account doesn't have the
https://cloud.google.com/sql/docs/mysql/project-access-control#roles[necessary IAM roles].

To find out what's causing the issue, you can enable DEBUG logging level at HikariCP by adding the
following logback.xml file to your application's resources, or only add the relevant set log level
line if you already have one logback.xml file:

[source, xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <include resource="org/springframework/boot/logging/logback/base.xml"/>
  <logger name="com.zaxxer.hikari.pool" level="DEBUG"/>
</configuration>
----
