= Spring Cloud GCP Config Client Starter Code Sample

This sample application demonstrates using the
link:../../spring-cloud-gcp-starters/spring-cloud-gcp-starter-config[Spring Cloud GCP Config Client Starter] in your code.

The same content is also available in the
https://codelabs.developers.google.com/codelabs/cloud-spring-runtime-config/index.html[Dynamic configuration for Spring Boot applications] codelab.

== Setup & Configuration
1. Checkout the code of this sample.
2. Enable the Google https://console.cloud.google.com/apis/api/runtimeconfig.googleapis.com/overview[Runtime Configuration API].
3. Create a configuration using the
https://cloud.google.com/sdk/[Google Cloud SDK].
+
....
$ gcloud beta runtime-config configs create myapp_prod
....
+
Then set the variables that your application will load:
+
....
$ gcloud beta runtime-config configs variables set \
  myapp.queue-size 25 \
  --config-name myapp_prod

$ gcloud beta runtime-config configs variables set \
  myapp.feature-x-enabled true \
  --config-name myapp_prod
....

4.  Update link:src/main/resources/bootstrap.properties[]:
+
....
spring.cloud.gcp.config.enabled=true
spring.cloud.gcp.config.name=myapp

#default profile = default
spring.cloud.gcp.config.profile=prod
....
5.  Notice that link:src/main/java/com/example/MyAppProperties.java[MyAppProperties.java]
uses `@ConfigurationProperties` to bind the `myapp` namespace from the environment.

6. Note that in order to expose /actuator/refresh endpoint,
link:src/resources/application.properties[application.properties] file
includes the following property:
+
....
management.endpoints.web.exposure.include=refresh
....
7.  Run the application using the `$ mvn spring-boot:run` command and
verify the values are set appropriately at http://localhost:8080/
8.  Update a property with `gcloud`:
+
....
$ gcloud beta runtime-config configs variables set \
  myapp.queue-size 200 \
  --config-name myapp_prod

$ gcloud beta runtime-config configs variables set \
  myapp.feature-x-enabled false \
  --config-name myapp_prod
....
9.  Send a POST request to the refresh endpoint:
+
....
$ curl -XPOST http://localhost:8080/actuator/refresh
....
10. Verify the values are updated at http://localhost:8080/
