= Code formatting guidelines

The directory src/eclipse has two files for use with code formatting, `eclipse-code-formatter.xml`
for the majority of the code formatting rules and `eclipse.importorder` to order the import
statements.

== Eclipse
Import these files by navigating `Windows -> Preferences` and then the menu items
`Preferences > Java > Code Style > Formatter` and `Preferences > Java > Code Style >
Organize Imports` respectively.

== IntelliJ IDEA
Install the plugin `Eclipse Code Formatter`. You can find it by searching in "Browse Repositories",
under `Settings > Plugins` within IDEA (Once installed, you will need to reboot IDEA for it to take
effect).

Then navigate to `Settings > Other Settings` (this might be under `Preferences` on Mac) and select
the Eclipse Code Formatter.
Select the `eclipse-code-formatter.xml` file for the field `Eclipse Java Formatter config file` and
the file `eclipse.importorder` for the field `Import order`.
Enable the `Eclipse code formatter` by clicking `Use the Eclipse code formatter` radio button at the
top of the page, then click the *OK* button.

* NOTE: If you configure the `Eclipse Code Formatter` from `File > Other Settings > Default
Settings`, it will set this policy across all of your IDEA projects.

* IDEA's "Optimize imports on the fly" option turned on interferes with the Eclipse code formatter
import optimization. Consider disabling the option if optimization does not yield the expected
results.

= Contribution workflow

When contributing to this repository, please observe the following guidelines.

1. Follow https://github.com/spring-projects/spring-framework/wiki/Spring-Framework-Code-Style[Spring
Framework codestyle] and enforce it through checkstyle and IDE

2. Create/assign a Github issue to yourself before starting work on a PR (whenever significant enough)

3. Reference issue(s) in the commit message / PR description to
https://help.github.com/articles/closing-issues-using-keywords/[automatically close] the issue when
PR is merged

4. Follow
https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#format-commit-messages[Spring
Commit Guidelines] for documenting commits, which will automatically pre-populate Github's PR title
and description

5. Use branches within spring-cloud-gcp to work on issues and allow multiple collaborators to add commits to a PR. (Using forks is also allowed, and necessary for external contributors)

6. For first-party contributors, the original PR author is responsible for merging the PR into master after getting approval from reviewer(s). (However, reviewer can merge, if the author is delaying.)

7. Always delete PR branch after close or merge. Github allows the branch to be restored if needed.

8. Protect master branch from direct commits.

9. Use Github's
https://help.github.com/articles/configuring-commit-squashing-for-pull-requests/[squash & merge
feature] when submitting PRs and enforce it through Github

10. When merging the PR, use the PR Title + Description as the commit message. See sample in the Appendix below.

