= Spring Cloud GCP release process

The actual release process is triggered by the release admin and happens together with the rest of the Spring Cloud release.
In order to simplify that process, here is a list of prerequisites to be performed before asking the release admin to run the release scripts.

. Ensure that modules that shouldn't be released have the `maven-deploy-plugin` configuration set to `<skip>true</skip>`.
For GA releases this should be configured under the `central` Maven profile.
+
[source,xml]
----
<build>
    <plugins>
        <plugin>
            <artifactId>maven-deploy-plugin</artifactId>
            <configuration>
                <skip>true</skip>
            </configuration>
        </plugin>
    </plugins>
</build>
----

. Wait for the release scripts to have been run by the release admin.

. Make sure that the release tag was automatically added by the release process.

. Make sure that the link:https://github.com/spring-io/initializr/blob/main/initializr-service/src/main/resources/application.yml[Spring Boot Initializr] is updated to support the new version of Spring Cloud GCP.

== Uploading Javadocs

After releasing a new version of Spring Cloud GCP, you will need to upload the javadocs for the released version.
By this point, we assume that a new release branch has been created for project (such as `1.1.x`, `1.2.x`, etc.).

The latest version of the docs can be accessed at the `latest/` url:
https://googleapis.dev/java/spring-cloud-gcp/latest/index.html

1. Locate and open the `prod:cloud-java-frameworks/spring-cloud-gcp-legacy/publish_javadoc` Kokoro job.

2. Add a new Github SCM and fill out the following parameters:

    - SCM Name: Set this to `spring-cloud-gcp`
    - Committish: Set this to the name of the new release branch or tag that you want to publish javadocs for (like `1.2.x` or `v1.2.1.RELEASE`).
      Note that you must already have the `.kokoro/` scripts in the branch that you wish to publish javadocs for.

3. Run the job.

4. Verify that the javadocs are published.
All uploaded javadocs will be published under the following URL:
+
----
https://googleapis.dev/java/spring-cloud-gcp/{BRANCH_VERSION_NAME}/index.html
----
+
Example: If you published the javadocs for version `1.2.2.BUILD-SNAPSHOT`, then the URL would be: https://googleapis.dev/java/spring-cloud-gcp/1.2.2.BUILD-SNAPSHOT/index.html

5. For GA releases, ask on the https://gitter.im/spring-cloud-gcp/Lobby[Spring Cloud GCP Gitter] for the Spring team to update the https://spring.io/projects/spring-cloud-gcp#learn[API Documentation link] to point to the published Javadocs of the correct version.
