= Spring Cloud GCP Firebase Authentication Sample application

This sample application demonstrates how to use link:../../spring-cloud-gcp-starters/spring-cloud-gcp-starter-security-firebase[Spring Cloud GCP Firebase Authentication Starter] to extract user identity from a signed https://firebase.google.com/[Firebase] JWT token.

The application provides a secured controller that can only be reached if a valid JWT token is sent as an HTTP Header.

This sample app provides simple login page using https://github.com/firebase/firebaseui-web[firebase-ui] to fetch the JWT token.

== Pre requisites

image:http://gstatic.com/cloudssh/images/open-btn.svg[link=https://ssh.cloud.google.com/cloudshell/editor?cloudshell_git_repo=https%3A%2F%2Fgithub.com%2FGoogleCloudPlatform%2Fspring-cloud-gcp&cloudshell_open_in_editor=spring-cloud-gcp-samples/spring-cloud-gcp-security-firebase-sample/README.adoc]

1. Create a new firebase project as instructed https://firebase.google.com/docs/web/setup[here]
2. Once you finish the process make sure you configure the following environment variables before running the app:
    a. FIREBASE_CONFIG_API_KEY: Should be your "apiKey" value (you can find it in Firebase console project settings in "Web API Key" field)
    b. FIREBASE_CONFIG_APP_ID: Should be your "appId" value for the application you set up in step 1.

3. Make sure that you are authenticated with `gcloud` and you have set the correct `projectId` to be the same project as your Firebase project.
This app uses default login and will rely on that to extract the `projectId` using the `GcpProjectIdProvider`
4. Go to your Firebase project, select the web application you have created and enable two providers: `Google` and `email`
5. (Optional) : You can add a few users to try this out if you rather not use the Google Provider authentication

== Running

`Make sure you executed steps 2 & 3 from prerequisites section`

. Run `$ mvn clean install` from the root directory of this project.

. Run `$ mvn clean spring-boot:run` in the same directory as this
sample (spring-cloud-gcp-samples/spring-cloud-gcp-security-firebase-sample)

. Open your browser at http://localhost:8080 or use the `Web Preview` button in Cloud Shell to preview the app
on port 8080.

. There's a single page app with an `ask` button, if you try to click it you should get an error message.

. Also try to access the secure endpoint via curl:

----
curl http://localhost:8080/answer
----

You should get a 403 error.

[start = 6]
. Now login using the button at the top right corner. You can choose between using a valid Google credential, or a user you have added via the Firebase authentication users menu.

. Once you are logged in, you should see a panel with the `curl` command.

. Try clicking the button again.

. You can also copy the `curl` command and execute it now on your console and you should be able to access the endpoint.



