= Spring Cloud GCP Storage Starter Example

This code sample demonstrates how to read and write files with the Spring Resource abstraction for
Google Cloud Storage using the
link:../../spring-cloud-gcp-starters/spring-cloud-gcp-starter-storage[Spring Cloud GCP Storage Starter].

This content is also available in the
https://codelabs.developers.google.com/codelabs/spring-cloud-gcp-gcs/index.html[Reading and Writing Files with Spring Resource Abstraction] codelab.

= Running the example

1. Make sure that you have the Cloud SDK configured by following https://cloud.google.com/sdk/docs/[these instructions].

2. Create a new bucket in Google Cloud Storage. You can use the `gsutil` command that comes with the
Cloud SDK.
+
```
$ BUCKET=spring-bucket-$USER
$ gsutil makebucket gs://$BUCKET
```

3. Transfer the local `my-file.txt` file to the bucket.
+
```
$ gsutil copy my-file.txt gs://$BUCKET
```

4. Edit the `src/main/resources/application.properties` and set the `gcs-resource-test-bucket` property to the name of your bucket that you created in Step 2.

5. Start the `GcsApplication` Spring Boot app.
+
```
$ mvn spring-boot:run
```

6. Navigate to http://localhost:8080/ in your browser to print the contents of the file you uploaded in 3.

7. To update the file contents, send a POST request to the same endpoint using `curl`:
+
```
$ curl -d 'new message' -H 'Content-Type: text/plain' localhost:8080
```
+
You should see a confirmation that the contents of the file were updated.
+
However, let's verify by going to http://localhost:8080/.
