:spring-data-commons-ref: https://docs.spring.io/spring-data/data-commons/docs/current/reference/html

== Spring Data Cloud Datastore

http://projects.spring.io/spring-data/[Spring Data] is an abstraction for storing and retrieving POJOs in numerous storage technologies.
Spring Cloud GCP adds Spring Data support for http://cloud.google.com/datastore/[Google Cloud Datastore].

Maven coordinates for this module only, using https://github.com/spring-cloud/spring-cloud-gcp/blob/master/spring-cloud-gcp-dependencies/pom.xml[Spring Cloud GCP BOM]:

[source,xml]
----
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-gcp-data-datastore</artifactId>
</dependency>
----

Gradle coordinates:

[source]
----
dependencies {
    compile group: 'org.springframework.cloud', name: 'spring-cloud-gcp-data-datastore'
}
----

We provide a link:../spring-cloud-gcp-starters/spring-cloud-gcp-starter-data-datastore[Spring Boot Starter for Spring Data Datastore], with which you can use our recommended auto-configuration setup.
To use the starter, see the coordinates below.


Maven:

[source,xml]
----
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-gcp-starter-data-datastore</artifactId>
</dependency>
----

Gradle:

[source,subs="normal"]
----
dependencies {
    compile group: 'org.springframework.cloud', name: 'spring-cloud-gcp-starter-data-datastore'
}
----

This setup takes care of bringing in the latest compatible version of Cloud Java Cloud Datastore libraries as well.

A https://github.com/spring-cloud/spring-cloud-gcp/tree/master/spring-cloud-gcp-samples/spring-cloud-gcp-data-datastore-sample[sample application] is available.

=== Configuration

To setup Spring Data Cloud Datastore, you have to configure the following:

* Setup the connection details to Google Cloud Datastore.

==== Cloud Datastore settings

You can the use link:../spring-cloud-gcp-starters/spring-cloud-gcp-starter-data-datastore[Spring Boot Starter for Spring Data Datastore] to autoconfigure Google Cloud Datastore in your Spring application.
It contains all the necessary setup that makes it easy to authenticate with your Google Cloud project.
The following configuration options are available:

|===
| Name | Description | Required | Default value
| `spring.cloud.gcp.datastore.enabled` | Enables the Cloud Datastore client | No | `true`
| `spring.cloud.gcp.datastore.project-id` | GCP project ID where the Google Cloud Datastore API
is hosted, if different from the one in the <<spring-cloud-gcp-core,Spring Cloud GCP Core Module>>
| No |
| `spring.cloud.gcp.datastore.credentials.location` | OAuth2 credentials for authenticating with the
Google Cloud Datastore API, if different from the ones in the
<<spring-cloud-gcp-core,Spring Cloud GCP Core Module>> | No |
| `spring.cloud.gcp.datastore.credentials.encoded-key` | Base64-encoded OAuth2 credentials for authenticating with the
Google Cloud Datastore API, if different from the ones in the
<<spring-cloud-gcp-core,Spring Cloud GCP Core Module>> | No |
| `spring.cloud.gcp.datastore.credentials.scopes` |
https://developers.google.com/identity/protocols/googlescopes[OAuth2 scope] for Spring Cloud GCP
Cloud Datastore credentials | No | https://www.googleapis.com/auth/datastore
| `spring.cloud.gcp.datastore.namespace` | The Cloud Datastore namespace to use | No | the Default namespace of Cloud Datastore in your GCP project
|===

==== Repository settings

Spring Data Repositories can be configured via the `@EnableDatastoreRepositories` annotation on your main `@Configuration` class.
With our Spring Boot Starter for Spring Data Cloud Datastore, `@EnableDatastoreRepositories` is automatically added.
It is not required to add it to any other class, unless there is a need to override finer grain configuration parameters provided by https://github.com/spring-cloud/spring-cloud-gcp/blob/master/spring-cloud-gcp-data-datastore/src/main/java/org/springframework/cloud/gcp/data/datastore/repository/config/EnableDatastoreRepositories.java[`@EnableDatastoreRepositories`].

==== Autoconfiguration

Our Spring Boot autoconfiguration creates the following beans available in the Spring application context:

- an instance of `DatastoreTemplate`
- an instance of all user defined repositories extending `CrudRepository` or `PagingAndSortingRepository`, when repositories are enabled
- an instance of `Datastore` from the Google Cloud Java Client for Datastore, for convenience and lower level API access


=== Object Mapping

Spring Data Cloud Datastore allows you to map domain POJOs to Cloud Datastore kinds and entities via annotations:

[source,java]
----
@Entity(name = "traders")
public class Trader {

	@Id
	@Field(name = "trader_id")
	String traderId;

	String firstName;

	String lastName;

	@Transient
	Double temporaryNumber;
}
----

Spring Data Cloud Datastore will ignore any property annotated with `@Transient`. These properties will not be written to or read from Cloud Datastore.

==== Constructors

Simple constructors are supported on POJOs.
The constructor arguments can be a subset of the persistent properties.
Every constructor argument needs to have the same name and type as a persistent property on the entity and the constructor should set the property from the given argument.
Arguments that are not directly set to properties are not supported.

[source,java]
----
@Entity(name = "traders")
public class Trader {

	@Id
	@Field(name = "trader_id")
	String traderId;

	String firstName;

	String lastName;

	@Transient
	Double temporaryNumber;

	public Trader(String traderId, String firstName) {
	    this.traderId = traderId;
	    this.firstName = firstName;
	}
}
----


==== Kind

The `@Entity` annotation can provide the name of the Cloud Datastore kind that stores instances of the annotated class, one per row.

==== Keys

`@Id` identifies the property corresponding to the ID value.

You must annotate one of your POJO's fields as the ID value, because every entity in Cloud Datastore requires a single ID value:

[source,java]
----
@Entity(name = "trades")
public class Trade {
	@Id
	@Field(name = "trade_id")
	String tradeId;

	@Field(name = "trader_id")
	String traderId;

	String action;

	Double price;

	Double shares;

	String symbol;
}
----


Datastore has automatic ID allocation. If a POJO instance is written to Cloud Datastore with `null` as the ID value, then Spring Data Cloud Datastore will obtain a newly allocated ID value from Cloud Datastore and set that in the POJO for saving.


==== Fields

All accessible properties on POJOs are automatically recognized as a Cloud Datastore field.
Field naming is generated by the `PropertyNameFieldNamingStrategy` by default defined on the `DatastoreMappingContext` bean.
The `@Field` annotation optionally provides a different field name than that of the property.


==== Embedded Entities

Fields marked as `@Embedded` are converted to `EntityValue` and stored inside the parent entity.
Multiple levels of embedded entities are supported.

NOTE: Embedded entities don't need to have `@Id` field, it is only required for top level entities.

Example:

We would like to store a binary tree in Cloud Datastore.
To do that, we need to create a node class and annotate children with `@Embedded`:

[source, java]
----
import org.springframework.cloud.gcp.data.datastore.core.mapping.Embedded;
import org.springframework.data.annotation.Id;

public class EmbeddableTreeNode {
	@Id
	long value;

	@Embedded
	EmbeddableTreeNode left;

	@Embedded
	EmbeddableTreeNode right;

	public EmbeddableTreeNode(long value, EmbeddableTreeNode left, EmbeddableTreeNode right) {
		this.value = value;
		this.left = left;
		this.right = right;
	}
}
----

Also, a collection of entities can be embedded; it will be converted to `ListValue` on write.

Example:

Instead of a binary tree from the previous example, we would like to store a general tree
(each node can have an arbitrary number of children) in Cloud Datastore.
To do that, we need to create a field of type `List<EmbeddableTreeNode>` and annotate it with `@Embedded`:

[source, java]
----
import org.springframework.cloud.gcp.data.datastore.core.mapping.Embedded;
import org.springframework.data.annotation.Id;

public class EmbeddableTreeNode {
	@Id
	long value;

	@Embedded
	List<EmbeddableTreeNode> children;

	public EmbeddableTreeNode(List<EmbeddableTreeNode> children;) {
		this.children = children;
	}
}
----

==== Relationships

This feature is not supported yet.

==== Supported Types

Spring Data Cloud Datastore supports the following types for regular fields and elements of collections:

[options="header"]
|===
| Type| Stored as
| `com.google.cloud.Timestamp`|com.google.cloud.datastore.TimestampValue
| `com.google.cloud.datastore.Blob`|com.google.cloud.datastore.BlobValue
| `com.google.cloud.datastore.LatLng`|com.google.cloud.datastore.LatLngValue
| `java.lang.Boolean`, `boolean`|com.google.cloud.datastore.BooleanValue
| `java.lang.Double`, `double`|com.google.cloud.datastore.DoubleValue
| `java.lang.Long`, `long`|com.google.cloud.datastore.LongValue
| `java.lang.Integer`, `int`|com.google.cloud.datastore.LongValue
| `java.lang.String`|com.google.cloud.datastore.StringValue
| `com.google.cloud.datastore.Entity`|com.google.cloud.datastore.EntityValue
| `com.google.cloud.datastore.Key`|com.google.cloud.datastore.KeyValue
| `byte[]`|com.google.cloud.datastore.BlobValue
|===

In addition, all types that can be converted to the ones listed in the table by
`org.springframework.core.convert.support.DefaultConversionService` are supported.

==== Custom types

Custom converters can be used extending the type support for user defined types.

. Converters need to implement the `org.springframework.core.convert.converter.Converter` interface in
both directions.

. The user defined type needs to be mapped to one of the basic types supported by Cloud Datastore.

. An instance of both Converters (read and write) needs to be passed to the `DatastoreCustomConversions` constructor,
which then has to be made available as a `@Bean` for `DatastoreCustomConversions`.

For example:

We would like to have a field of type  `Album` on our `Singer` POJO and want it to be stored as a string property:
[source, java]
----
@Entity
public class Singer {

	@Id
	String singerId;

	String name;

	Album album;
}
----

Where Album is a simple class:

[source, java]
----
public class Album {
	String albumName;

	LocalDate date;
}
----

We have to define the two converters:

[source, java]
----
	//Converter to write custom Album type
	static final Converter<Album, String> ALBUM_STRING_CONVERTER =
			new Converter<Album, String>() {
				@Override
				public String convert(Album album) {
					return album.getAlbumName() + " " + album.getDate().format(DateTimeFormatter.ISO_DATE);
				}
			};

	//Converters to read custom Album type
	static final Converter<String, Album> STRING_ALBUM_CONVERTER =
			new Converter<String, Album>() {
				@Override
				public Album convert(String s) {
					String[] parts = s.split(" ");
					return new Album(parts[0], LocalDate.parse(parts[parts.length - 1], DateTimeFormatter.ISO_DATE));
				}
			};
----

That will be configured in our `@Configuration` file:

[source, java]
----
@Configuration
public class ConverterConfiguration {
	@Bean
	public DatastoreCustomConversions datastoreCustomConversions() {
		return new DatastoreCustomConversions(
				Arrays.asList(
						ALBUM_STRING_CONVERTER,
						STRING_ALBUM_CONVERTER));
	}
}
----

==== Collections and arrays

Arrays and collections (types that implement `java.util.Collection`) of supported types are supported.
They are stored as `com.google.cloud.datastore.ListValue`.
Elements are converted to Cloud Datastore supported types individually. `byte[]` is an exception, it is converted to
`com.google.cloud.datastore.Blob`.


==== Custom Converter for collections
Users can provide converters from  `List<?>` to the custom collection type.
Only read converter is necessary, the Collection API is used on the write side to convert a collection to
the internal list type.

Collection converters need to implement the `org.springframework.core.convert.converter.Converter` interface.


Example:

Let's improve the Singer class from the previous example.
Instead of a field of type `Album`,
we would like to have a field of type `ImmutableSet<Album>`:

[source, java]
----
@Entity
public class Singer {

	@Id
	String singerId;

	String name;

	ImmutableSet<Album> albums;
}
----

We have to define a read converter only:
[source, java]
----
static final Converter<List<?>, ImmutableSet<?>> LIST_IMMUTABLE_SET_CONVERTER =
			new Converter<List<?>, ImmutableSet<?>>() {
				@Override
				public ImmutableSet<?> convert(List<?> source) {
					return ImmutableSet.copyOf(source);
				}
			};
----

And add it to the list of custom converters:
[source, java]
----
@Configuration
public class ConverterConfiguration {
	@Bean
	public DatastoreCustomConversions datastoreCustomConversions() {
		return new DatastoreCustomConversions(
				Arrays.asList(
						LIST_IMMUTABLE_SET_CONVERTER,

						ALBUM_STRING_CONVERTER,
						STRING_ALBUM_CONVERTER));
	}
}
----

=== Datastore Template

`DatastoreOperations` and its implementation, `DatastoreTemplate`, provides the Template pattern familiar to Spring developers.

Using the auto-configuration provided by Spring Boot Starter for Datastore, your Spring application context will contain a fully configured `DatastoreTemplate` object that you can autowire in your application:

[source,java]
----
@SpringBootApplication
public class DatastoreTemplateExample {

	@Autowired
	DatastoreTemplate datastoreTemplate;

	public void doSomething() {
		this.datastoreTemplate.deleteAll(Trader.class);
		//...
		Trader t = new Trader();
		//...
		this.datastoreTemplate.save(t);
		//...
		List<Trader> traders = datastoreTemplate.findAll(Trader.class);
		//...
	}
}
----

The Template API provides convenience methods for:

- Write operations (saving and deleting)
- Locking read-write transactions

==== GQL Query

This feature is not supported yet.

==== Find by ID(s)

Datstore reading a single entity or multiple entities in a kind.

Using `DatastoreTemplate` you can execute reads, for example:

[source,java]
----
Trader trader = this.datastoreTemplate.findById("trader1", Trader.class);

List<Trader> traders = this.datastoreTemplate.findAllById(ImmutableList.of("trader1", "trader2"), Trader.class);

List<Trader> allTraders = this.datastoreTemplate.findAll(Trader.class);
----

Cloud Datastore executes key-based reads with strong consistency, but queries with eventual consistency.
In the example above the first two reads utilize keys, while the third is executed using a query based on the corresponding Kind of `Trader`.


===== Indexes

By default, all fields are indexed. To disable indexing on a particular field, `@Unindexed` annotation can be used.

Example:
[source, java]
----
import org.springframework.cloud.gcp.data.datastore.core.mapping.Unindexed;

public class ExampleItem {
	long indexedField;

	@Unindexed
	long unindexedField;
}
----

===== Read with offsets and limits

This feature is not supported yet.

===== Sorting

This feature is not supported yet.

===== Partial read

This feature is not supported yet.

==== Write / Update

The write methods of `DatastoreOperations` accept a POJO and writes all of its properties to Datastore.
The required Datastore kind and entity metadata is obtained from the given object's actual type.

If a POJO was retrieved from Datastore and its ID value was changed and then written or updated, the operation will occur as if against a row with the new ID value.
The entity with the original ID value will not be affected.

[source, java]
----
Trader t = new Trader();
this.datastoreTemplate.save(t);
----

The `save` method behaves as update-or-insert.

===== Partial Update

This feature is not supported yet.

==== Transactions

Read and write transactions are provided by `DatastoreOperations` via the `performTransaction` method:

[source,java]
----

@Autowired
DatastoreOperations myDatastoreOperations;

public String doWorkInsideTransaction() {
  return myDatastoreOperations.performTransaction(
    transactionDatastoreOperations -> {
      // work with transactionDatastoreOperations here. It is also a DatastoreOperations object.

      return "transaction completed";
    }
  );
}
----

The `performTransaction` method accepts a `Function` that is provided an instance of a
`DatastoreOperations` object. The final returned value and type of the function is determined by the user.
You can use this object just as you would a regular `DatastoreOperations` with
an exception:

- It cannot perform sub-transactions.

=== Repositories

{spring-data-commons-ref}/#repositories[Spring Data Repositories] are an abstraction that can reduce boilerplate code.

For example:

[source,java]
----
public interface TraderRepository extends CrudRepository<Trader, String> {
}
----

Spring Data generates a working implementation of the specified interface, which can be autowired into an application.

The `Trader` type parameter to `CrudRepository` refers to the underlying domain type.
The second type parameter, `String` in this case, refers to the type of the key of the domain type.

[source,java]
----
public class MyApplication {

	@Autowired
	TraderRepository traderRepository;

	public void demo() {

		this.traderRepository.deleteAll(); //defined on CrudRepository
		String traderId = "demo_trader";
		Trader t = new Trader();
		t.traderId = traderId;
		this.tradeRepository.save(t); //defined on CrudRepository

		Iterable<Trader> allTraders = this.traderRepository.findAll(); //defined on CrudRepository

		int count = this.traderRepository.count();
	}
}

----

==== Transactions

These transactions work very similarly to
those of `DatastoreOperations`, but is specific to the repository's domain type and provides repository functions
instead of template functions.

For example, this is a read-write transaction:

[source,java]
----

@Autowired
DatastoreRepository myRepo;

public String doWorkInsideTransaction() {
  return myRepo.performTransaction(
    transactionDatastoreRepo -> {
      // work with the single-transaction transactionDatastoreRepo here. This is a DatastoreRepository object.

      return "transaction completed";
    }
  );
}
----

==== Query methods by convention

[source, java]
----
public interface TradeRepository extends CrudRepository<Trade, String[]> {
    List<Trader> findByAction(String action);

  int countByAction(String action);

  boolean existsByAction(String action);

  List<Trade> findTop3ByActionAndSymbolAndPriceGreaterThanAndPriceLessThanOrEqualOrderBySymbolDesc(
  			String action, String symbol, double priceFloor, double priceCeiling);
}
----

In the example above the {spring-data-commons-ref}/#repositories.query-methods[query methods] in `TradeRepository` are generated based on the name of the methods using the{spring-data-commons-ref}#repositories.query-methods.query-creation[Spring Data Query creation naming convention].

Cloud Datastore only supports filter components joined by AND, and the following operations:

* `equals`
* `greater than or equals`
* `greater than`
* `less than or equals`
* `less than`
* `is null`

After writing a custom repository interface specifying just the signatures of these methods, implementations are generated for you and can be used with an auto-wired instance of the repository.

==== Custom GQL query methods

Custom GQL queries can be mapped to repository methods in one of two ways:

 * `namedQueries` properties file
 * using the `@Query` annotation

===== Query methods with annotation

Using the `@Query` annotation:

The names of the tags of the GQL correspond to the `@Param` annotated names of the method parameters.

[source, java]
----
public interface TraderRepository extends CrudRepository<Trader, String> {

  @Query("SELECT * FROM traders WHERE name = @trader_name")
  List<Trader> tradersByName(@Param("trader_name) String traderName);

}
----

The following parameter types are supported:

* `com.google.cloud.Timestamp`
* `com.google.cloud.datastore.Blob`
* `com.google.cloud.datastore.Key`
* `com.google.cloud.datastore.Cursor`
* `java.lang.Boolean`
* `java.lang.Double`
* `java.lang.Long`
* `java.lang.String`

With the exception of `Cursor`, array forms of each of the types are also supported.

If you would like to obtain the count of items of a query or if there are any items returned by the query, set the `count = true` or `exists = true` properties of the `@Query` annotation, respectively.
The return type of the query method in these cases should be an integer type or a boolean type.

Cloud Datastore provides provides the `SELECT __key__ FROM ...` special column for all kinds that retrieves the `Key`s of each row. Selecting this special `__key__` column is especially useful and efficient for `count` and `exists` queries.

===== Query methods with named queries properties

You can also specify queries with Cloud Datastore parameter tags and SpEL expressions in properties files.

By default, the `namedQueriesLocation` attribute on `@EnableDatastoreRepositories` points to the `META-INF/datastore-named-queries.properties` file.
You can specify the query for a method in the properties file by providing the GQL as the value for the "interface.method" property:

[source, properties]
----
Trader.fetchByName=SELECT * FROM traders WHERE name = @tag0
----

[source, java]
----
public interface TraderRepository extends CrudRepository<Trader, String> {

	// This method uses the query from the properties file instead of one generated based on name.
	List<Trader> fetchByName(@Param("tag0") String traderName);

}
----

==== Projections

This feature is not supported yet.

==== REST Repositories

This feature is not supported yet.
