== Dependency Management

The Spring Cloud GCP Bill of Materials (BOM) contains the versions of all the dependencies it uses.

If you’re a Maven user, adding the following to your pom.xml file will allow you to not specify any
Spring Cloud GCP dependency versions.
Instead, the version of the BOM you’re using determines the versions of the used dependencies.

[source,xml,subs="normal"]
----
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-gcp-dependencies</artifactId>
            <version>{project-version}</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>
----

In the following sections, the Maven dependency snippets will assume you are using the Spring Cloud
GCP BOM and the dependency versions are omitted.

Gradle users can achieve the same kind of BOM experience using Spring's
https://github.com/spring-gradle-plugins/dependency-management-plugin[dependency-management-plugin]
Gradle plugin.

[#pivotal-snapshot-repository]
=== Pivotal Snapshot Repository

At the time of writing, the Spring Cloud GCP artifacts are hosted at Pivotal's Snapshot repository.

In order to use Pivotal's Snapshot Repository in Maven, add the following to your `pom.xml` file:

[source]
----
<repositories>
    <repository>
        <id>spring-snapshots</id>
        <name>Spring Snapshots</name>
        <url>https://repo.spring.io/snapshot</url>
        <snapshots>
            <enabled>true</enabled>
        </snapshots>
        <releases>
            <enabled>false</enabled>
        </releases>
    </repository>
</repositories>
----

Gradle users must add a repository to the `repositories` section of their `build.gradle` file:

[source]
----
repositories {
    ...
    maven {
        url "http://repo.spring.io/snapshot"
    }
}
----
