== Getting started

There are many available resources to get you up to speed with our libraries as quickly as possible.

=== Spring Initializr

There are three entries in http://start.spring.io/[Spring Initializr] for Spring Cloud GCP:

- GCP Support
- GCP Messaging
- GCP Storage

The GCP Support entry contains auto-configuration support for every Spring Cloud GCP integration.
Most of the autoconfiguration code is only enabled if other dependencies are added to the classpath.

|===
|Spring Cloud GCP Starter |Required dependencies

|Config
|_None_

|Spanner
|- org.springframework.cloud:spring-cloud-gcp-data-spanner

- org.springframework:spring-tx

|Logging
|- ch.qos.logback.contrib:logback-json-classic

- com.google.cloud:google-cloud-logging-logback

- org.springframework:spring-webmvc

|Pub/Sub
|org.springframework.cloud:spring-cloud-gcp-pubsub

|SQL - MySql
|- org.springframework.boot:spring-boot-starter-jdbc

- com.google.cloud.sql:mysql-socket-factory

- mysql:mysql-connector-java

|SQL - PostgreSQL
|- org.springframework.boot:spring-boot-starter-jdbc

- com.google.cloud.sql:postgres-socket-factory

- org.postgresql:postgresql

|Storage
|org.springframework.cloud:spring-cloud-gcp-storage

|Trace
|- org.springframework.cloud:spring-cloud-starter-sleuth

- com.google.cloud:google-cloud-trace

- com.google.cloud.trace.v1:sink

- com.google.api:gax

|===

The GCP Messaging entry adds the GCP Support entry and all the required dependencies so that the Google Cloud Pub/Sub integrations work out of the box.

The GCP Storage entry adds the GCP Support entry and all the required dependencies so that the Google Cloud Storage integrations work out of the box.

=== Code Samples

There are https://github.com/spring-cloud/spring-cloud-gcp/tree/master/spring-cloud-gcp-samples[code samples] available that demonstrate the usage of all our integrations.

=== Code Challenges

In a code challenge, you perform a task step by step, using one integration.
There are a number of challenges available in the https://codelabs.developers.google.com/spring[Google Developers Codelabs] page.

=== Getting Started Guides

A Spring Getting Started guide on messaging with Spring Integration Channel Adapters for Google Cloud Pub/Sub is available from https://spring.io/guides/gs/messaging-gcp-pubsub/[Spring Guides].
