:spring-security-ref: https://docs.spring.io/spring-security/site/docs/current/reference/htmlsingle/
:spring-security-javadoc: https://docs.spring.io/spring-security/site/docs/current/api/org/springframework/security/

== Google Cloud IAP Authentication

https://cloud.google.com/iap/[Cloud Identity-Aware Proxy (IAP)] provides a security layer over applications deployed to Google Cloud.

The IAP starter uses {spring-security-ref}#oauth2resourceserver[Spring Security OAuth 2.0 Resource Server] functionality to automatically extract user identity from the proxy-injected `x-goog-iap-jwt-assertion` HTTP header.

The following claims are validated automatically:

 * Issue time
 * Expiration time
 * Issuer

Additionally, Audience (`"aud"`) validation is enabled when the application is running on AppEngine/ComputeEngine/Kubernetes, or when a custom audience is provided through `spring.cloud.gcp.security.iap.audience` property.
The custom property overrides automatic environment-based checks.

NOTE: If you create a custom {spring-security-javadoc}config/annotation/web/configuration/WebSecurityConfigurerAdapter.html[`WebSecurityConfigurerAdapter`], enable extracting user identity by adding `.oauth2ResourceServer().jwt()` configuration to the {spring-security-javadoc}config/annotation/web/builders/HttpSecurity.html[`HttpSecurity`] object.
 If no custom {spring-security-javadoc}config/annotation/web/configuration/WebSecurityConfigurerAdapter.html[`WebSecurityConfigurerAdapter`] is present, nothing needs to be done because Spring Boot will add this customization by default.

A https://github.com/spring-cloud/spring-cloud-gcp/tree/master/spring-cloud-gcp-samples/spring-cloud-gcp-security-iap-sample[sample application] is available.

Starter Maven coordinates, using https://github.com/spring-cloud/spring-cloud-gcp/blob/master/spring-cloud-gcp-dependencies/pom.xml[Spring Cloud GCP BOM]:

[source,xml]
----
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-gcp-starter-security-iap</artifactId>
</dependency>
----

Starter Gradle coordinates:

[source]
----
dependencies {
    compile group: 'org.springframework.cloud', name: 'spring-cloud-gcp-starter-security-iap'
}
----

== Configuration
The following properties are available.

CAUTION: Modifying registry, algorithm, and header properties might be useful for testing, but the defaults should not be changed in production.

|===
|Name |Description |Required |Default

|`spring.cloud.gcp.security.iap.registry`
|Link to JWK public key registry.
|true
|`https://www.gstatic.com/iap/verify/public_key-jwk`

|`spring.cloud.gcp.security.iap.algorithm`
|Encryption algorithm used to sign the JWK token.
|true
|`ES256`

|`spring.cloud.gcp.security.iap.header`
|Header from which to extract the JWK key.
|true
|`x-goog-iap-jwt-assertion`

|`spring.cloud.gcp.security.iap.issuer`
|JWK issuer to verify.
|true
|`https://cloud.google.com/iap`

|`spring.cloud.gcp.security.iap.audience`
|Custom JWK audience to verify.
Note that without this option, the audience is automatically determined for applications deployed to App Engine/Compute Engine/Kubernetes Engine.
|false
|

|===
