== Spring Resources

https://docs.spring.io/spring/docs/current/spring-framework-reference/html/resources.html[Spring Resources]
are an abstraction to gain access to a number of low-level resources, such as file system files,
classpath files, servlet context-relative files, etc. Spring Cloud GCP adds a new resource type: a
Google Cloud Storage (GCS) object.

=== Google Cloud Storage

The Spring Resource Abstraction for Google Cloud Storage allows GCS objects to be accessed by their
GCS URL:

[source,java]
----
@Value("gs://[YOUR_GCS_BUCKET]/[GCS_FILE_NAME]")
private Resource gcsResource;
----

This creates a `Resource` object that can be used to read the object, among
https://docs.spring.io/spring/docs/current/spring-framework-reference/html/resources.html#resources-resource[other possible operations].

It is also possible to write to a `Resource`, although a cast to `WriteableResource` is required.

[source,java]
----
try (OutputStream os = ((WritableResource) gcsResource).getOutputStream()) {
  os.write("foo".getBytes());
}
----

The Spring Boot Starter for Google Cloud Storage auto-configures the `Storage` bean required by the
`spring-cloud-gcp-storage` module, based on the `CredentialsProvider` provided by the Spring Boot
GCP Core starter.

