== Spring Resources

https://docs.spring.io/spring/docs/current/spring-framework-reference/html/resources.html[Spring Resources]
are an abstraction for a number of low-level resources, such as file system files, classpath files,
servlet context-relative files, etc.
Spring Cloud GCP adds a new resource type: a Google Cloud Storage (GCS) object.

A Spring Boot starter is provided to auto-configure the various Storage components.

Maven coordinates, using Spring Cloud GCP BOM:

[source,xml]
----
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-gcp-starter-storage</artifactId>
</dependency>
----

Gradle coordinates:

[source,subs="normal"]
----
dependencies {
    compile group: 'org.springframework.cloud', name: 'spring-cloud-gcp-starter-storage', version: '{project-version}'
}
----


=== Google Cloud Storage

The Spring Resource Abstraction for Google Cloud Storage allows GCS objects to be accessed by their
GCS URL:

[source,java]
----
@Value("gs://[YOUR_GCS_BUCKET]/[GCS_FILE_NAME]")
private Resource gcsResource;
----

This creates a `Resource` object that can be used to read the object, among
https://docs.spring.io/spring/docs/current/spring-framework-reference/html/resources.html#resources-resource[other possible operations].

It is also possible to write to a `Resource`, although a cast to `WriteableResource` is required.

[source,java]
----
try (OutputStream os = ((WritableResource) gcsResource).getOutputStream()) {
  os.write("foo".getBytes());
}
----

The Spring Boot Starter for Google Cloud Storage auto-configures the `Storage` bean required by the
`spring-cloud-gcp-storage` module, based on the `CredentialsProvider` provided by the Spring Boot
GCP Core starter.

=== Configuration

The Spring Boot Starter for Google Cloud Storage provides the following configuration options:

[source,yaml]
----
spring.cloud.gcp.storage.auto-create-files=false #optional, default true
spring.cloud.gcp.storage.credentials.location=[CREDENTIALS_RESOURCE_PATH] #optional
spring.cloud.gcp.storage.credentials.scopes=[COMMA_DELIMITED_SCOPE_LIST] #optional
----

`spring.cloud.gcp.storage.auto-create-files` creates files on Google Cloud Storage when writes are
made to non-existent files.

`spring.cloud.gcp.storage.credentials.location` and `spring.cloud.gcp.storage.credentials.scopes`
are overrides to the same options in the <<spring-cloud-gcp-core,Spring Cloud GCP Core Module>>.
