== Spring Cloud Sleuth

https://cloud.spring.io/spring-cloud-sleuth/[Spring Cloud Sleuth] is an instrumentation framework for Spring Boot
applications. It captures trace informations and can forward traces to services like Zipkin for storage and
analysis.

Google Cloud Platform provides its own managed distributed tracing service called
https://cloud.google.com/trace/[Stackdriver Trace]. Instead of running and maintaining your own Zipkin instance and
storage, you can use Stackdriver Trace to store traces, view trace details, generate latency distributions graphs,
and generate performance regression reports.

This Spring Cloud GCP starter can forward Spring Cloud Sleuth traces to Stackdriver Trace without an intermediary
Zipkin server.

Maven coordinates, using Spring Cloud GCP BOM:


[source,xml]
----
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-gcp-starter-trace</artifactId>
</dependency>
----

Gradle coordinates:

[source,subs="normal"]
----
dependencies {
    compile group: 'org.springframework.cloud', name: 'spring-cloud-gcp-starter-trace'
}
----

You must enable Stackdriver Trace API from the Google Cloud Console in order to capture traces. Navigate to the
https://console.cloud.google.com/apis/api/cloudtrace.googleapis.com/overview[Stackdriver Trace API] for your project
and make sure it’s enabled.

[NOTE]
====
If you are already using a Zipkin server capturing trace information from multiple platform/frameworks, you also use a
https://cloud.google.com/trace/docs/zipkin[Stackdriver Zipkin proxy] to forward those traces to Stackdriver Trace
without modifying existing applications.
====

=== Spring Boot Starter for Stackdriver Trace
Spring Boot Starter for Stackdriver Trace uses Spring Cloud Sleuth and auto-configures a https://github.com/openzipkin/zipkin-gcp/blob/master/sender-stackdriver/src/main/java/zipkin2/reporter/stackdriver/StackdriverSender.java[StackdriverSender] that sends the Sleuth’s trace information to Stackdriver Trace.

All configurations are optional:

|===
| Name | Description | Required | Default value
| `spring.cloud.gcp.trace.enabled` | Auto-configure Spring Cloud Sleuth to send traces to Stackdriver Trace. | No | `true`
| `spring.cloud.gcp.trace.project-id` | Overrides the project ID from the <<spring-cloud-gcp-core,Spring Cloud GCP Module>> | No |
| `spring.cloud.gcp.trace.credentials.location` | Overrides the credentials location from the <<spring-cloud-gcp-core,Spring Cloud GCP Module>> | No |
| `spring.cloud.gcp.trace.credentials.scopes` | Overrides the credentials scopes from the <<spring-cloud-gcp-core,Spring Cloud GCP Module>> | No |
| `spring.cloud.gcp.trace.num-executor-threads` | Number of threads used by the Trace executor | No | 4
| `spring.cloud.gcp.trace.authority` | HTTP/2 authority the channel claims to be connecting to. | No |
| `spring.cloud.gcp.trace.compression` | Name of the compression to use in Trace calls | No |
| `spring.cloud.gcp.trace.deadline-ms` | Call deadline in milliseconds | No |
| `spring.cloud.gcp.trace.max-inbound-size` | Maximum size for inbound messages | No |
| `spring.cloud.gcp.trace.max-outbound-size` | Maximum size for outbound messages | No |
| `spring.cloud.gcp.trace.wait-for-ready` | https://github.com/grpc/grpc/blob/master/doc/wait-for-ready.md[Waits for the channel to be ready] in case of a transient failure | No | `false`
|===

You can use core Spring Cloud Sleuth properties to control Sleuth’s sampling rate, etc.
Read https://cloud.spring.io/spring-cloud-sleuth/[Sleuth documentation] for more information on Sleuth configurations.

For example, when you are testing to see the traces are going through, you can set the sampling rate to 100%.

[source]
----
spring.sleuth.sampler.probability=1                     # Send 100% of the request traces to Stackdriver.
spring.sleuth.web.skipPattern=(^cleanup.*|.+favicon.*)  # Ignore some URL paths.
----

Spring Cloud GCP Trace does override some Sleuth configurations:

- Always uses 128-bit Trace IDs. This is required by Stackdriver Trace.
- Does not use Span joins. Span joins will share the span ID between the client and server Spans. Stackdriver requires that every Span ID within a Trace to be unique, so Span joins are not supported.
- Uses `StackdriverHttpClientParser` and `StackdriverHttpServerParser` by default to populate Stackdriver related fields.

=== Integration with Logging

Logs can also be associated with traces. See link:logging.adoc[Stackdriver Logging Support] for how to configure logging such that it carries Trace ID metadata.
