= Spring Boot Starter for Google Stackdriver Trace

Maven coordinates, using Spring Cloud GCP BOM:

[source,xml]
----
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-gcp-starter-trace</artifactId>
</dependency>
----

Gradle coordinates:

[source]
----
dependencies {
    compile group: 'org.springframework.cloud', name: 'spring-cloud-gcp-starter-trace'
}
----

Spring Boot Starter for Stackdriver Trace uses Spring Cloud Sleuth and auto-configures a
https://github.com/openzipkin/zipkin-reporter-java/blob/master/core/src/main/java/zipkin2/reporter/Reporter.java[Reporter]
that sends the Sleuth’s trace information to Stackdriver Trace.

This starter will send traces asynchronously using a buffered trace consumer that auto-flushes when its buffered trace
messages exceed its buffer size or have been buffered for longer than its scheduled delay.


There are several parameters you can use to tune the Stackdriver Trace adapter. All configurations are optional:

|===
| Name | Description | Required | Default value
| `spring.cloud.gcp.trace.enabled` |
Auto-configure Spring Cloud Sleuth to send traces to Stackdriver Trace. | No | `true`
| `spring.cloud.gcp.trace.executor-threads` |
Number of threads to use by the underlying gRPC channel to send the trace request to Stackdriver. |
No | `4`
| `spring.cloud.gcp.trace.buffer-size-bytes` |
Buffer size in bytes. Traces will be flushed to Stackdriver when buffered trace messages exceed this
size. | No | 1% of Runtime.totalMemory()
| `spring.cloud.gcp.trace.scheduled-delay-seconds` |
Buffered trace messages will be flushed to Stackdriver when buffered longer than scheduled delays
(in seconds) even if the buffered message size didn't exceed the buffer size. | No | `10`
| `spring.cloud.gcp.trace.project-id` |
Overrides the project ID from the <<spring-cloud-gcp-core,Spring Cloud GCP Module>> | No |
| `spring.cloud.gcp.trace.credentials.location` |
Overrides the credentials location from the <<spring-cloud-gcp-core,Spring Cloud GCP Module>> |
No |
| `spring.cloud.gcp.trace.credentials.scopes` |
Overrides the credentials scopes from the <<spring-cloud-gcp-core,Spring Cloud GCP Module>> |
No |
|===

You can use core Spring Cloud Sleuth properties to control Sleuth's sampling rate, etc.
Read https://cloud.spring.io/spring-cloud-sleuth/[Sleuth documentation] for more information
on Sleuth configurations.

For example, when you are testing to see the traces are going through, you can set the sampling rate to 100%.

----
spring.sleuth.sampler.probability=1                             # Send 100% of the request traces to Stackdriver.
spring.sleuth.web.skipPattern=(^cleanup.*|.+favicon.*)          # Ignore some URL paths
----

== Enable APIs
You must enable Stackdriver Trace API from the Google Cloud Console in order to capture traces.
Navigate to the link:https://console.cloud.google.com/apis/api/cloudtrace.googleapis.com/overview[Stackdriver Trace API]
for your project and make sure it's enabled.

