= Google Cloud Pub/Sub Spring Boot Starter

Maven coordinates, using Spring Cloud GCP BOM:

[source,xml]
----
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-gcp-starter-pubsub</artifactId>
</dependency>
----

Gradle coordinates:

[source]
----
dependencies {
    compile group: 'org.springframework.cloud', name: 'spring-cloud-gcp-starter-pubsub'
}
----


This starter provides auto-configured instances of `PubSubTemplate` and `PubSubAdmin`.

The following properties are optional:
[source,yaml]
----
spring.cloud.gcp.pubsub.subscriber-executor-threads=[SUBSCRIBER_EXECUTOR_THREADS] #optional, default 4
spring.cloud.gcp.pubsub.publisher-executor-threads=[PUBLISHER_EXECUTOR_THREADS] #optional, default 4
spring.cloud.gcp.pubsub.project-id=[PUBSUB_GCP_PROJECT_ID] #optional
spring.cloud.gcp.pubsub.credentials.location=[CREDENTIALS_RESOURCE_PATH] #optional
spring.cloud.gcp.pubsub.credentials.scopes=[COMMA_DELIMITED_SCOPE_LIST] #optional
----

`spring.cloud.gcp.pubsub.subscriber-executor-threads` is the number of threads used by the
subscriber executor.
Likewise, `spring.cloud.gcp.pubsub.publisher-executor-threads` is the number of threads used by the
publisher executor.

`spring.cloud.gcp.pubsub.project-id` and `spring.cloud.gcp.pubsub.credentials.location` and
`spring.cloud.gcp.pubsub.credentials.scopes` are overrides to the GCP project ID and credentials in
the link:../spring-cloud-gcp-starter-core/README.adoc[Core Starter], in case the Google Cloud
Pub/Sub service is hosted from a different GCP project ID.
