= Google Cloud Pub/Sub Spring Boot Starter

Maven coordinates, using Spring Cloud GCP BOM:

[source,xml]
----
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-gcp-starter-pubsub</artifactId>
</dependency>
----

Gradle coordinates:

[source]
----
dependencies {
    compile group: 'org.springframework.cloud', name: 'spring-cloud-gcp-starter-pubsub', version: '1.0.0.BUILD-SNAPSHOT'
}
----


This starter provides auto-configured instances of `PubSubTemplate` and `PubSubAdmin`.

The following properties are optional:
[source,yaml]
----
spring.cloud.gcp.pubsub.subscriber-executor-threads=[SUBSCRIBER_EXECUTOR_THREADS]
spring.cloud.gcp.pubsub.publisher-executor-threads=[PUBLISHER_EXECUTOR_THREADS]
spring.cloud.gcp.pubsub.project-id=[PUBSUB_GCP_PROJECT_ID]
spring.cloud.gcp.pubsub.credentials-location=[CREDENTIALS_FILESYSTEM_PATH]
----

`spring.cloud.gcp.pubsub.subscriber-executor-threads` is the number of threads used by the
subscriber executor.
Likewise, `spring.cloud.gcp.pubsub.publisher-executor-threads` is the number of threads used by the
publisher executor.
The default value for both of these properties is 4.

`spring.cloud.gcp.pubsub.project-id` and `spring.cloud.gcp.pubsub.credentials-location` are
overrides to the GCP project ID and credentials in the
link:../spring-cloud-gcp-starter-core/README.adoc[Core Starter], in case the Google Cloud Pub/Sub service is
hosted from a different GCP project ID.
