= Spring Cloud GCP Stream for Pub/Sub Dead Letter Topic Code Sample

This code sample demonstrates how to use the Spring Cloud Stream binder for Google Cloud Pub/Sub with Dead Letter Topics.

The sample app prompts a user for a message and user name.
That data is added to a `UserMessage` object, together with the time of message creation, and is sent through Google Cloud Pub/Sub to a sink that `nack()`s the message.
Pub/Sub will attempt to redeliver the message up to maximum number of retries before routing it to the configured dead letter topic.\
This sample app also listens to this dead letter topic, and logs any messages received.

If the topics for the sink, source, and dead letter topic do not exist, the binder will automatically create them in Google Cloud Pub/Sub based on the values in link:src/main/resources/application.properties[application.properties].

== Running the code sample

1. Configure your credentials and project ID by following link:../../docs/src/main/asciidoc/core.adoc#project-id[these instructions].
+
Alternatively, if you have the https://cloud.google.com/sdk/[Google Cloud SDK] installed and initialized, and are logged in with https://developers.google.com/identity/protocols/application-default-credentials[application default credentials], Spring will auto-discover those parameters for you.

2. Set your project ID using the `spring.cloud.gcp.project-id` property in link:src/main/resources/application.properties[application.properties] or use the `gcloud config set project [PROJECT_ID]` Cloud SDK command.

3. In the link:src/main/resources/application.properties[application.properties] file, a topic and a dead letter topic are already preconfigured for you.
The topics will be created in your account if they do not already exist.

4. Run the `mvn clean spring-boot:run` in the root of the code sample to get the app running.

5. Browse `localhost:8080`, type in a message, a user name, and press the `Post it!` button.

6. Verify in your app's logs that a similar message was posted:
+
```
Publishing message from batman
Nacking message (attempt 1) from batman at 2021-03-10T15:33:00.479420: to the batcave!
Nacking message (attempt 2) from batman at 2021-03-10T15:33:00.479420: to the batcave!
Nacking message (attempt 3) from batman at 2021-03-10T15:33:00.479420: to the batcave!
Nacking message (attempt 4) from batman at 2021-03-10T15:33:00.479420: to the batcave!
Nacking message (attempt 5) from batman at 2021-03-10T15:33:00.479420: to the batcave!
Nacking message (attempt 6) from batman at 2021-03-10T15:33:00.479420: to the batcave!
Received message on dead letter topic from batman: to the batcave!
```
