= Spring Cloud GCP Logging Starter Example

This sample application demonstrates using the
link:../../spring-cloud-gcp-starters/spring-cloud-gcp-starter-logging[Spring Cloud GCP Logging
Starter] to store and group logs by trace ID, with the Google Stackdriver Logging API.

== Setup & Configuration

image:http://gstatic.com/cloudssh/images/open-btn.svg[link=https://ssh.cloud.google.com/cloudshell/editor?cloudshell_git_repo=https%3A%2F%2Fgithub.com%2FGoogleCloudPlatform%2Fspring-cloud-gcp&cloudshell_open_in_editor=spring-cloud-gcp-samples/spring-cloud-gcp-logging-sample/README.adoc]

1. Create a Google Cloud Platform Project
2. Have the https://cloud.google.com/sdk/[Google Cloud SDK] installed, initialized and logged in with https://developers.google.com/identity/protocols/application-default-credentials[application default credentials].
3. Check that the https://console.cloud.google.com/apis/library/logging.googleapis.com/?q=logging[Stackdriver Logging API is enabled].
4. Run `$ mvn clean install` from the root directory of the project.

== Running the Example
Run the following command from the same directory as this sample application (spring-cloud-gcp-samples/spring-cloud-gcp-logging-sample):

----
$ mvn spring-boot:run
----

Then, issue a request containing the `x-cloud-trace-context` header to the `localhost:8080/log` endpoint and verify that a label appears in Stackdriver:

----
$ curl --header "x-cloud-trace-context: [Some-Trace-ID]" localhost:8080/log
----

To see the logged lines, navigate to the https://console.cloud.google.com/logs/viewer[Logging section of the Cloud Console].
Select the `Global` resource and look under the `spring.log` channel to see the logged text.

=== Running on Google Cloud Platform

Deploy to App Engine:

----
$ mvn clean package appengine:deploy -Dapp.deploy.projectId=$PROJECT_ID -Dapp.deploy.version=$VERSION
----

If your application is deployed to Google App Engine (GAE) or Google Kubernetes Engine (GKE), you will instead find the logs under the deployment's resource in the Stackdriver UI under the `spring.log` channel.
You can further narrow down the log by request by using the following filtering text that takes advantage of the trace ID label in each logged line.
For example, if deployed to App Engine, you can use the following to filter by the trace ID:

----
 resource.type="gae_app"
 logName="projects/[Your-Project-ID]/logs/spring.log"
 labels."appengine.googleapis.com/trace_id"="[Trace-ID-Of-Request]"
----

Expand the log entry labels and note that `appengine.googleapis.com/trace_id` label is set to the same value for both log messages.
The trace ID header `x-cloud-trace-context` is set automatically when deployed to App Engine.

NOTE: When running on GAE or GKE, remember to remove the `CONSOLE` appender. Otherwise, logs are duplicated in Cloud Logging (once in the `spring.log` stream and once in the `stdout` stream).
