= Spring Resource Abstraction for Google Cloud Storage

Maven coordinates, using Spring Cloud GCP BOM:

[source,xml]
----
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-gcp-storage</artifactId>
</dependency>
----

Gradle coordinates:

[source]
----
dependencies {
    compile group: 'org.springframework.cloud', name: 'spring-cloud-gcp-starter-storage'
}
----


Enables the Spring Resource abstraction to run on Google Cloud Storage.

You can use the `@Value` annotation

[source,java]
----
@Value("gs://[YOUR_GCS_BUCKET]/[GCS_FILE_NAME]")
private Resource gcsResource;
----

or the Spring application context

[source,java]
----
SpringApplication.run(...).getResource("gs://[YOUR_GCS_BUCKET]/[GCS_FILE_NAME]");
----

You can also use this resource to write to a Google Cloud Storage object:

[source,java]
----
try (OutputStream os = ((WritableResource) gcsResource).getOutputStream()) {
  os.write("foo".getBytes());
}
----

By default a new file is created if the resource refers to a file that does not exist when getting
the output stream. This can be overriden by setting `spring.cloud.gcp.storage.auto-create-files`
to `false`.

If the path refers to an object on Google Cloud Storage (as opposed to a bucket), then the resource
can be cast as a `GoogleStorageResourceObject` and the `getGoogleStorageObject` method can be called
to obtain a https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-storage/src/main/java/com/google/cloud/storage/Blob.java[`Blob`].
This type represents a GCS file, which has associated https://cloud.google.com/storage/docs/gsutil/addlhelp/WorkingWithObjectMetadata[metadata], such as content-type, that can be set.
The `createSignedUrl` method can also be used to obtain https://cloud.google.com/storage/docs/access-control/signed-urls[signed URLs] for GCS objects.
However, creating signed URLs requires that the resource was created using service account credentials.
