= Spring Resource Abstraction for Google Cloud Storage

Maven coordinates, using Spring Cloud GCP BOM:

[source,xml]
----
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-gcp-storage</artifactId>
</dependency>
----

Gradle coordinates:

[source]
----
dependencies {
    compile group: 'org.springframework.cloud', name: 'spring-cloud-gcp-starter-storage'
}
----


Enables the Spring Resource abstraction to run on Google Cloud Storage.

You can use the `@Value` annotation

[source,java]
----
@Value("gs://[YOUR_GCS_BUCKET]/[GCS_FILE_NAME]")
private Resource gcsResource;
----

or the Spring application context

[source,java]
----
SpringApplication.run(...).getResource("gs://[YOUR_GCS_BUCKET]/[GCS_FILE_NAME]");
----

You can also use this resource to write to a Google Cloud Storage object:

[source,java]
----
try (OutputStream os = ((WritableResource) gcsResource).getOutputStream()) {
  os.write("foo".getBytes());
}
----

By default a new file is created if the resource refers to a file that does not exist when getting
the output stream. This can be overriden by setting `spring.cloud.gcp.storage.auto-create-files`
to `false`.

If the path refers to an object on Google Cloud Storage (as opposed to a bucket), then the resource
can be cast as a `GoogleStorageResourceObject` and the `getGoogleStorageObject` method can be called
to obtain a
https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-storage/src/main/java/com/google/cloud/storage/Blob.java[`Blob`].
This type represents a GCS file, which has associated
https://cloud.google.com/storage/docs/gsutil/addlhelp/WorkingWithObjectMetadata[metadata], such as
content-type, that can be set.
The `createSignedUrl` method can also be used to obtain
https://cloud.google.com/storage/docs/access-control/signed-urls[signed URLs] for GCS objects.
However, creating signed URLs requires that the resource was created using service account
credentials.

== Spring Integration Storage Channel Adapters

The channel adapters for Google Cloud Storage allow you to read and write files to Google Cloud
Storage through `MessageChannels`.

Spring Cloud GCP provides two inbound adapters, `GcsInboundFileSynchronizingMessageSource` and
`GcsStreamingMessageSource`, and one outbound adapter, `GcsMessageHandler`.

=== Inbound channel adapter

The Google Cloud Storage inbound channel adapter polls a Google Cloud Storage bucket for new files
and sends each of them in a `Message` payload to the `MessageChannel` specified in the
`@InboundChannelAdapter` annotation.
The files are temporarily stored in a folder in the local file system.

Here is an example of how to configure a Google Cloud Storage inbound channel adapter.

[source,java]
----
@Bean
@InboundChannelAdapter(channel = "new-file-channel", poller = @Poller(fixedDelay = "5000"))
public MessageSource<File> synchronizerAdapter(Storage gcs) {
  GcsInboundFileSynchronizer synchronizer = new GcsInboundFileSynchronizer(gcs);
  synchronizer.setRemoteDirectory("your-gcs-bucket");

  GcsInboundFileSynchronizingMessageSource synchAdapter =
          new GcsInboundFileSynchronizingMessageSource(synchronizer);
  synchAdapter.setLocalDirectory(new File("local-directory"));

  return synchAdapter;
}
----

=== Inbound streaming channel adapter

The inbound streaming channel adapter is similar to the normal inbound channel adapter, except it
does not require files to be stored in the file system.

Here is an example of how to configure a Google Cloud Storage inbound streaming channel adapter.

[source,java]
----
@Bean
@InboundChannelAdapter(channel = "streaming-channel", poller = @Poller(fixedDelay = "5000"))
public MessageSource<InputStream> streamingAdapter(Storage gcs) {
  GcsStreamingMessageSource adapter =
          new GcsStreamingMessageSource(new GcsRemoteFileTemplate(new GcsSessionFactory(gcs)));
  adapter.setRemoteDirectory("your-gcs-bucket");
  return adapter;
}
----

=== Outbound channel adapter

The outbound channel adapter allows files to be written to Google Cloud Storage.
When it receives a `Message` containing a payload of type `File`, it writes that file to the Google
Cloud Storage bucket specified in the adapter.

Here is an example of how to configure a Google Cloud Storage outbound channel adapter.

[source,java]
----
@Bean
@ServiceActivator(inputChannel = "writeFiles")
public MessageHandler outboundChannelAdapter(Storage gcs) {
  GcsMessageHandler outboundChannelAdapter = new GcsMessageHandler(new GcsSessionFactory(gcs));
  outboundChannelAdapter.setRemoteDirectoryExpression(new ValueExpression<>("your-gcs-bucket"));

  return outboundChannelAdapter;
}
----
