= Spring Cloud GCP Stream Binder for Pub/Sub Code Sample

This code sample demonstrates how to use the Spring Cloud Stream binder for Google Cloud Pub/Sub.
The sample app prompts a user for a message and their user name.
That data is added to a `UserMessage` object, together with the time of message creation, and is sent through Google Cloud Pub/Sub to a sink which simply logs the message.

If the topic and subscription for the sink and source don't exist, the binder will automatically create them in Google Cloud Pub/Sub based on the values in link:src/main/resources/application.properties[application.properties].

The `SourceExample` in this sample is the same as in link:../spring-cloud-gcp-pubsub-binder-sample/[Streaming PubSub Binder Sample]; there is nothing polling-specific in it.
`SinkExample`, however, describes a poll-style interaction with a Pub/Sub subscription.

The following code, combined with `@EnableScheduling` annotation in `PubSubBinderApplication`, triggers retrieval of a message every second.
Note that `destIn` bean is provided by Spring Cloud Stream, using the _spring-cloud-gcp-pubsub-stream-binder_ dependency for the bean implementation.

[source,java]
----
@Scheduled(fixedRate = 1000)
public void poller() {

    destIn.poll(this.messageHandler, ParameterizedTypeReference.forType(UserMessage.class));
}
----


== Running the code sample

1. Configure your credentials and project ID by following link:../../docs/src/main/asciidoc/core.adoc#project-id[these instructions].
+
Alternatively, if you have the https://cloud.google.com/sdk/[Google Cloud SDK] installed and initialized, and are logged in with https://developers.google.com/identity/protocols/application-default-credentials[application default credentials], Spring will auto-discover those parameters for you.

2. Set your project ID using the `spring.cloud.gcp.project-id` property in link:src/main/resources/application.properties[application.properties] or use the `gcloud config set project [PROJECT_ID]` Cloud SDK command.

3. Set the topic and subscription name in the link:src/main/resources/application.properties[application.properties] file.
+
If you're relying on the binder automatically creating the topic and subscription for you, they need to have the same name so that the messages are properly routed.
+
Alternatively, you can manually create the topic and subscription from the https://console.cloud.google.com/cloudpubsub[Google Cloud Console].

4. Run the `mvn clean spring-boot:run` in the root of the code sample to get the app running.

5. Browse `localhost:8080`, type in a message and a user name and press the `Post it!` button.

6. Verify in your app's logs that a similar message was posted:
+
`New message received from [USERNAME] via polling: [MESSAGE] at [TIME_MESSAGE_SENT]`
