= Spring Cloud GCP Pub/Sub

Maven coordinates, using Spring Cloud GCP BOM:

[source,xml]
----
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-gcp-pubsub</artifactId>
</dependency>
----

Gradle coordinates:

[source]
----
dependencies {
    compile group: 'org.springframework.cloud', name: 'spring-cloud-gcp-pubsub'
}
----


Provides a simplified abstraction to interact with Google Cloud Pub/Sub. Using this abstraction
allows user code to be independent from the underlying Google Cloud Pub/Sub API semantics. It's
currently possible to publish messages to a Google Cloud Pub/Sub topic and to create new topics and
subscriptions.

You can refer to the `PubSubTemplate` and `PubSubAdmin` classes for more details on the
functionality provided by this module.

== Spring Integration Pub/Sub Channel Adapters

Provides adapters for Spring Messaging channels to exchange messages via Google Cloud Pub/Sub.
Makes extensive use of the constructs provided by the Spring Cloud GCP Pub/Sub module, like
`PubSubOperations`.

The outbound channel adapter, `PubSubMessageHandler`, publishes messages asynchronously by default.
A publish timeout can be configured for synchronous publishing. If none is provided, the adapter
waits indefinitely for a response.

It is possible to set user-defined callbacks for the `publish()` call in `PubSubMessageHandler`
through the `setPublishFutureCallback()` method.
These are useful to process the message ID, in case of success, or the error if any was thrown.

Refer to the https://spring.io/guides/gs/spring-cloud-gcp/[Spring getting started guide] to learn
how to use the adapters.
