= Spring Cloud GCP Spanner Starter Example

This code sample demonstrates how to read and write POJOs from Google Spanner using the Spring
Data Spanner module
link:../../spring-cloud-gcp-starters/spring-cloud-gcp-starter-data-spanner[Spring Cloud GCP Spanner Starter].

= Running the example


. Setup the database
.. Create a new Spanner instance named "spring-demo".
.. Create with a database called "trades"
.. Create a table, also named "trades".
You can define the table via the following DDL
```
CREATE TABLE trades (
	action STRING(15),
	symbol STRING(10),
	curve ARRAY<FLOAT64>,
	price FLOAT64,
	shares FLOAT64,
	person STRING(MAX),
	trader_id STRING(128),
) PRIMARY KEY (action, symbol)
```
[start=2]
. https://cloud.google.com/sdk/gcloud/reference/auth/application-default/login[If
you are authenticated in the Cloud SDK], your credentials will be automatically found by the Spring
Boot Starter for Google Cloud Spanner.
+
Alternatively, http://console.cloud.google.com/iam-admin/serviceaccounts[create a service account from the Google Cloud Console] and download its private key.
+
Then, uncomment the `spring.cloud.gcp.spanner.credentials.location` property in the
link:src/main/resources/application.properties[application.properties] file and fill its value with the path to your service account private key on your local file system, prepended with `file:`.

. Run the `SpannerRepositoryExample` or the `SpannerTemplateExample` Spring Boot console apps. This causes the app to generate sample `Trade`
objects filled with some demo data and persists them to the Spanner table created earlier.
These POJOs are then retrieved and their contents are printed in the browser.
