= Spring Cloud GCP Spanner Starter Example

This code sample demonstrates how to read and write POJOs from Google Spanner using the Spring
Data Spanner module
link:../../spring-cloud-gcp-starters/spring-cloud-gcp-starter-data-spanner[Spring Cloud GCP Spanner Starter].

= Running the example

1. Make sure that you have the Cloud SDK configured by following https://cloud.google.com/sdk/docs/[these instructions].

2. Setup the database

a.) Create a new Spanner instance named "spring-demo". For testing, choose the cheapest region possible for you and only 1 region instance should suffice.
b.) Create with a database called "trades"
c.) Create a table, also named "trades". You can define the table via the following DDL

```
CREATE TABLE trades (
	action STRING(15),
	symbol STRING(10),
	curve ARRAY<FLOAT64>,
	price FLOAT64,
	shares FLOAT64,
	test INT64,
	testDate DATE,
	trader_id STRING(128),
) PRIMARY KEY (action, symbol)
```

3. Place your project ID in the `spring.cloud.gcp.spanner.projectId` setting in `application.properties`
if you are not providing the project ID from a JSON key file or the SDK.

4. Run the `SpannerRepositoryExample` or the `SpannerTemplateExample` Spring Boot console apps. This causes the app to generate sample `Trade`
objects filled with some demo data and persists them to the Spanner table created earlier.
These POJOs are then retrieved and their contents are printed in the browser.
