= Spring Cloud GCP Spanner Starter Example

This code sample demonstrates how to read and write POJOs from Google Spanner using the Spring
Data Spanner module
link:../../spring-cloud-gcp-starters/spring-cloud-gcp-starter-data-spanner[Spring Cloud GCP Spanner Starter].

= Running the example


. Setup the database
.. Create a new Spanner instance named "spring-demo".
.. Create with a database called "trades"
.. Create two tables called "traders" and "trades" using the schema below:
```
CREATE TABLE traders (
    trader_id STRING(MAX),
    first_name STRING(100),
    last_name STRING(100),
) PRIMARY KEY (trader_id);

CREATE TABLE trades (
    trader_id STRING(MAX),
    trade_id STRING(MAX),
    action STRING(15),
    symbol STRING(10),
    curve ARRAY<FLOAT64>,
    price FLOAT64,
    shares FLOAT64,
    person STRING(MAX)
) PRIMARY KEY (trader_id, trade_id)
```
[start=2]
. https://cloud.google.com/sdk/gcloud/reference/auth/application-default/login[If
you are authenticated in the Cloud SDK], your credentials will be automatically found by the Spring
Boot Starter for Google Cloud Spanner.
+
Alternatively, http://console.cloud.google.com/iam-admin/serviceaccounts[create a service account from the Google Cloud Console] and download its private key.
+
Then, uncomment the `spring.cloud.gcp.spanner.credentials.location` property in the
link:src/main/resources/application.properties[application.properties] file and fill its value with the path to your service account private key on your local file system, prepended with `file:`.

. Run the `SpannerRepositoryExample` or the `SpannerTemplateExample` Spring Boot console apps. This causes the app to generate sample `Trade`
objects filled with some demo data and persists them to the Spanner table created earlier.
These POJOs are then retrieved and their contents are printed in the browser.


Note that the sample application, still running, also provides REST endpoints.
For example, you can retrieve all `Trade` objects in the repository by using
`curl http://localhost:8080/trades`, or any specific trade via
`curl http://localhost:8080/trades/<trader_id>,<trade_id>`. This is achieved using
https://projects.spring.io/spring-data-rest/:[Spring Data REST] and the `@RepositoryRestResource`
annotation.

You can also write trades using
`curl -XPOST -H"Content-Type: application/json" -d@test.json http://localhost:8080/trades/`
where the file `test.json` holds the JSON representation of a `Trade` object.
