= Spring Cloud GCP Spanner Starter Example

This code sample demonstrates how to read and write POJOs from Google Spanner using the Spring
Data Spanner module
link:../../spring-cloud-gcp-starters/spring-cloud-gcp-starter-data-spanner[Spring Cloud GCP Spanner Starter].

= Running the example

1. Make sure that you have the Cloud SDK configured by following https://cloud.google.com/sdk/docs/[these instructions].

2. Setup the database

a.) Create a new Spanner instance named "spring-demo". For testing, choose the cheapest region possible for you and only 1 region instance should suffice.
b.) Create with a database called "trades"
c.) Create a table, also named "trades". You can define the table via the following DDL

```
CREATE TABLE trades (
  action STRING(15),
  price FLOAT64,
  shares FLOAT64,
  symbol STRING(10),
  trader_id STRING(128)
) PRIMARY KEY (action, symbol)
```

3. Place your project ID in the `spring.cloud.gcp.spanner.projectId` setting in `application.properties`
if you are not providing the project ID from a JSON key file or the SDK.

4. Run the `SpannerApplication` Spring Boot app.

5. Navigate to http://localhost:8080/ in your browser. This causes the app to generate five `Trade`
objects filled with some demo data and persists them to the Spanner table created earlier.
These POJOs are then retrieved and their contents are printed in the browser.
