= Spring Integration Channel Adapters for Google Cloud Pub/Sub

Maven coordinates, using Spring Cloud GCP BOM:

[source,xml]
----
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-gcp-integration</artifactId>
</dependency>
----

Gradle coordinates:

[source]
----
dependencies {
    compile group: 'org.springframework.cloud', name: 'spring-cloud-gcp-integration', version: '1.0.0.M1'
}
----


Provides adapters for Spring Messaging channels to exchange messages via Google Cloud Pub/Sub.
Makes extensive use of the constructs provided by the Spring Cloud GCP Pub/Sub module, like
`PubSubOperations`.

The outbound channel adapter, `PubSubMessageHandler`, publishes messages asynchronously by default.
A publish timeout can be configured for synchronous publishing. If none is provided, the adapter
waits indefinitely for a response.

It is possible to set user-defined callbacks for the `publish()` call in `PubSubMessageHandler`
through the `setPublishFutureCallback()` method.
These are useful to process the message ID, in case of success, or the error if any was thrown.

Refer to the https://spring.io/guides/gs/spring-cloud-gcp/[Spring getting started guide] to learn
how to use the adapters.
