== Cloud Firestore

Spring Cloud GCP provides a convenience starter which automatically configures authentication settings and client objects needed to begin using https://cloud.google.com/firestore/[Google Cloud Firestore].

See https://cloud.google.com/firestore/docs/[documentation] to learn more about Cloud Firestore.

To begin using this library, add the `spring-cloud-gcp-starter-data-firestore` artifact to your project.

Maven coordinates, using <<getting-started.adoc#_bill_of_materials, Spring Cloud GCP BOM>>:

[source,xml]
----
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-gcp-starter-firestore</artifactId>
</dependency>
----

Gradle coordinates:

[source]
----
dependencies {
  compile group: 'org.springframework.cloud', name: 'spring-cloud-gcp-starter-firestore'
}
----

=== Sample

A https://github.com/spring-cloud-gcp/spring-cloud-gcp-samples/spring-cloud-gcp-firestore-sample[sample application] is available.

=== Using Cloud Firestore

The starter automatically configures and registers a `Firestore` bean in the Spring application context. To start using it, simply use the `@Autowired` annotation.

[source,java]
----
@Autowired
Firestore firestore;

private void writeDocumentFromObject() throws ExecutionException, InterruptedException {
    // Add document data with id "joe" to collection "users" using a custom User class
    User data = new User("Joe",
            Arrays.asList(
                new Phone(12345, PhoneType.CELL),
                new Phone(54321, PhoneType.WORK)));

    // asynchronously write data
    ApiFuture<WriteResult> result = docRef.set(data);

    // result.get() blocks on response
    LOGGER.info"Update time: " + result.get().getUpdateTime());
}

private void readDocumentToObject() throws ExecutionException, InterruptedException {
    ApiFuture<DocumentSnapshot> documentSnapshotApiFuture = this.firestore.document("users/joe").get();

    User user = documentSnapshotApiFuture.get().toObject(User.class);

    /*
        do something with the user object
        ...
    */
}
----

=== Configuration

The Spring Boot starter for Google Cloud Firestore provides the following configuration options:

|===
| Name | Description | Required | Default value
| `spring.cloud.gcp.firestore.enabled` | Enables or disables Pub/Sub auto-configuration | No | `true`
| `spring.cloud.gcp.firestore.project-id` | GCP project ID where the Google Cloud Firestore API is hosted, if different from the one in the <<spring-cloud-gcp-core,Spring Cloud GCP Core Module>> | No |


