:spring-data-commons-ref: https://docs.spring.io/spring-data/data-commons/docs/current/reference/html

== Spring Data Cloud Firestore
NOTE: Currently some features are not supported: query by example, projections, and auditing.

https://projects.spring.io/spring-data/[Spring Data] is an abstraction for storing and retrieving POJOs in numerous storage technologies.
Spring Cloud GCP adds Spring Data Reactive Repositories support for https://cloud.google.com/firestore/[Google Cloud Firestore] in native mode, providing reactive template and repositories support.
To begin using this library, add the `spring-cloud-gcp-data-firestore` artifact to your project.

Maven coordinates for this module only, using <<getting-started.adoc#_bill_of_materials, Spring Cloud GCP BOM>>:


[source,xml]
----
<dependency>
  <groupId>com.google.cloud</groupId>
  <artifactId>spring-cloud-gcp-data-firestore</artifactId>
</dependency>
----

Gradle coordinates:

[source]
----
dependencies {
  implementation("org.springframework.cloud:spring-cloud-gcp-data-firestore")
}
----

We provide a Spring Boot Starter for Spring Data Firestore, with which you can use our recommended auto-configuration setup. To use the starter, see the coordinates below.

[source,xml]
----
<dependency>
  <groupId>com.google.cloud</groupId>
  <artifactId>spring-cloud-gcp-starter-data-firestore</artifactId>
</dependency>
----

Gradle coordinates:

[source]
----
dependencies {
  implementation("org.springframework.cloud:spring-cloud-gcp-starter-data-firestore")
}
----

=== Configuration
==== Properties
The Spring Boot starter for Google Cloud Firestore provides the following configuration options:

|=========================================================
| Name | Description | Required | Default value
| `spring.cloud.gcp.firestore.enabled` | Enables or disables Firestore auto-configuration | No | `true`
| `spring.cloud.gcp.firestore.project-id` | GCP project ID where the Google Cloud Firestore API is hosted, if different from the one in the <<spring-cloud-gcp-core,Spring Cloud GCP Core Module>> | No |
| `spring.cloud.gcp.firestore.emulator.enabled` | Enables the usage of an emulator. If this is set to true, then you should set the `spring.cloud.gcp.firestore.host-port` to the host:port of your locally running emulator instance | No | `false`
| `spring.cloud.gcp.firestore.host-port` | The host and port of the Firestore service; can be overridden to specify connecting to an already-running https://firebase.google.com/docs/emulator-suite/install_and_configure[Firestore emulator] instance. | No | `firestore.googleapis.com:443` (the host/port of official Firestore service)
| `spring.cloud.gcp.firestore.credentials.location` | OAuth2 credentials for authenticating with the Google Cloud Firestore API, if different from the ones in the <<spring-cloud-gcp-core,Spring Cloud GCP Core Module>> | No |
| `spring.cloud.gcp.firestore.credentials.encoded-key` | Base64-encoded OAuth2 credentials for authenticating with the Google Cloud Firestore API, if different from the ones in the <<spring-cloud-gcp-core,Spring Cloud GCP Core Module>> | No |
| `spring.cloud.gcp.firestore.credentials.scopes` | https://developers.google.com/identity/protocols/googlescopes[OAuth2 scope] for Spring Cloud GCP Cloud Firestore credentials | No | https://www.googleapis.com/auth/datastore
|=========================================================


==== Supported types
You may use the following field types when defining your persistent entities or when binding query parameters:

* `Long`
* `Integer`
* `Double`
* `Float`
* `String`
* `Boolean`
* `Character`
* `Date`
* `Map`
* `List`
* `Enum`
* `com.google.cloud.Timestamp`
* `com.google.cloud.firestore.GeoPoint`
* `com.google.cloud.firestore.Blob`

==== Reactive Repository settings

Spring Data Repositories can be configured via the `@EnableReactiveFirestoreRepositories` annotation on your main `@Configuration` class.
With our Spring Boot Starter for Spring Data Cloud Firestore, `@EnableReactiveFirestoreRepositories` is automatically added.
It is not required to add it to any other class, unless there is a need to override finer grain configuration parameters provided by https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/master/spring-cloud-gcp-data-firestore/src/main/java/com/google/cloud/spring/data/firestore/repository/config/EnableReactiveFirestoreRepositories.java[`@EnableReactiveFirestoreRepositories`].

==== Autoconfiguration

Our Spring Boot autoconfiguration creates the following beans available in the Spring application context:

- an instance of `FirestoreTemplate`
- instances of all user defined repositories extending `FirestoreReactiveRepository` (an extension of `ReactiveCrudRepository` with additional Cloud Firestore features) when repositories are enabled
- an instance of https://developers.google.com/resources/api-libraries/documentation/firestore/v1/java/latest/[`Firestore`] from the Google Cloud Java Client for Firestore, for convenience and lower level API access

=== Object Mapping

Spring Data Cloud Firestore allows you to map domain POJOs to https://firebase.google.com/docs/firestore/data-model#collections[Cloud Firestore collections] and documents via annotations:

[source,java,indent=0]
----
import com.google.cloud.firestore.annotation.DocumentId;
import com.google.cloud.spring.data.firestore.Document;

include::{project-root}/spring-cloud-gcp-data-firestore/src/test/java/com/google/cloud/spring/data/firestore/entities/User.java[tag=class_definition]
----

`@Document(collectionName = "usersCollection")` annotation configures the collection name for the documents of this type.
This annotation is optional, by default the collection name is derived from the class name.

`@DocumentId` annotation marks a field to be used as document id.
This annotation is required and the annotated field can only be of `String` type.

NOTE: If the property annotated with `@DocumentId` is `null` the document id is generated automatically when the entity is saved.

NOTE: Internally we use Firestore client library object mapping. See https://developers.google.com/android/reference/com/google/firebase/firestore/package-summary[the documentation] for supported annotations.

==== Embedded entities and lists
Spring Data Cloud Firestore supports embedded properties of custom types and lists.
Given a custom POJO definition, you can have properties of this type or lists of this type in your entities.
They are stored as embedded documents (or arrays, correspondingly) in the Cloud Firestore.

Example:

[source,java,indent=0]
----
include::{project-root}/spring-cloud-gcp-data-firestore/src/test/java/com/google/cloud/spring/data/firestore/entities/User.java[tag=embedded_class_collections]
----

=== Reactive Repositories

https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/repository/reactive/ReactiveCrudRepository.html[Spring Data Repositories] is an abstraction that can reduce boilerplate code.

For example:

[source,java]
----

include::{project-root}/spring-cloud-gcp-data-firestore/src/test/java/com/google/cloud/spring/data/firestore/entities/UserRepository.java[tag=repository]

----

Spring Data generates a working implementation of the specified interface, which can be autowired into an application.

The `User` type parameter to `FirestoreReactiveRepository` refers to the underlying domain type.

NOTE: You can refer to nested fields using https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repositories.query-methods.query-property-expressions[Spring Data JPA Property Expressions]

[source,java]
----
public class MyApplication {

include::{project-root}/spring-cloud-gcp-data-firestore/src/test/java/com/google/cloud/spring/data/firestore/it/FirestoreRepositoryIntegrationTests.java[tag=autowire]

include::{project-root}/spring-cloud-gcp-data-firestore/src/test/java/com/google/cloud/spring/data/firestore/it/FirestoreRepositoryIntegrationTests.java[tag=repository_built_in]
}

----

Repositories allow you to define custom Query Methods (detailed in the following sections) for retrieving and counting based on filtering and paging parameters.

NOTE: Custom queries with `@Query` annotation are not supported since there is no query language in Cloud Firestore


=== Firestore Operations & Template

`FirestoreOperations` and its implementation, `FirestoreTemplate`, provides the Template pattern familiar to Spring developers.

Using the auto-configuration provided by Spring Data Cloud Firestore, your Spring application context will contain a fully configured `FirestoreTemplate` object that you can autowire in your application:

[source,java]
----
@SpringBootApplication
public class FirestoreTemplateExample {

	@Autowired
	FirestoreOperations firestoreOperations;

	public Mono<User> createUsers() {
		return this.firestoreOperatons.save(new User("Alice", 29))
			.then(this.firestoreOperatons.save(new User("Bob", 60)));
	}

	public Flux<User> findUsers() {
		return this.firestoreOperatons.findAll(User.class);
	}

	public Mono<Long> removeAllUsers() {
		return this.firestoreOperatons.deleteAll(User.class);
	}
}
----

The Template API provides support for:

- Read and write operations
- <<Transactions>>
- <<Subcollections>> operations


=== Query methods by convention

[source, java]
----
public class MyApplication {
include::{project-root}/spring-cloud-gcp-data-firestore/src/test/java/com/google/cloud/spring/data/firestore/it/FirestoreRepositoryIntegrationTests.java[tag=repository_part_tree]
}
----

In the example above the query method implementations in `UserRepository` are generated based on the name of the methods using the {spring-data-commons-ref}#repositories.query-methods.query-creation[Spring Data Query creation naming convention].

Cloud Firestore only supports filter components joined by AND, and the following operations:

* `equals`
* `greater than or equals`
* `greater than`
* `less than or equals`
* `less than`
* `is null`
* `contains` (accepts a `List` with up to 10 elements, or a singular value)
* `in` (accepts a `List` with up to 10 elements)

NOTE:  If `in` operation is used in combination with `contains` operation, the argument to `contains` operation has to be a singular value.

After writing a custom repository interface specifying just the signatures of these methods, implementations are generated for you and can be used with an auto-wired instance of the repository.

=== Transactions
Read-only and read-write transactions are provided by `TransactionalOperator` (see this https://spring.io/blog/2019/05/16/reactive-transactions-with-spring[blog post] on reactive transactions for details).
In order to use it, you would need to autowire `ReactiveFirestoreTransactionManager` like this:

[source, java]
----
public class MyApplication {
include::{project-root}/spring-cloud-gcp-data-firestore/src/test/java/com/google/cloud/spring/data/firestore/it/FirestoreRepositoryIntegrationTests.java[tag=autowire_tx_manager]
}
----

After that you will be able to use it to create an instance of `TransactionalOperator`.
Note that you can switch between read-only and read-write transactions using `TransactionDefinition` object:

[source, java, indent=0]
----
include::{project-root}/spring-cloud-gcp-data-firestore/src/test/java/com/google/cloud/spring/data/firestore/it/FirestoreRepositoryIntegrationTests.java[tag=repository_transactional_operator]
----

When you have an instance of  `TransactionalOperator`, you can invoke a sequence of Firestore operations in a transaction by using `operator::transactional`:

[source, java, indent=0]
----
include::{project-root}/spring-cloud-gcp-data-firestore/src/test/java/com/google/cloud/spring/data/firestore/it/FirestoreRepositoryIntegrationTests.java[tag=repository_operations_in_a_transaction]
----

NOTE: Read operations in a transaction can only happen before write operations.
All write operations are applied atomically.
Read documents are locked until the transaction finishes with a commit or a rollback, which are handled by Spring Data.
If an `Exception` is thrown within a transaction, the rollback operation is performed.
Otherwise, the commit operation is performed.

==== Declarative Transactions with @Transactional Annotation

This feature requires a bean of `SpannerTransactionManager`, which is provided when using `spring-cloud-gcp-starter-data-firestore`.

`FirestoreTemplate` and `FirestoreReactiveRepository` support running methods with the `@Transactional` https://docs.spring.io/spring/docs/current/spring-framework-reference/data-access.html#transaction-declarative[annotation] as transactions.
If a method annotated with `@Transactional` calls another method also annotated, then both methods will work within the same transaction.

One way to use this feature is illustrated here. You would need to do the following:

. Annotate your configuration class with the `@EnableTransactionManagement` annotation.

. Create a service class that has methods annotated with `@Transactional`:

[source, java, indent=0]
----
include::{project-root}/spring-cloud-gcp-data-firestore/src/test/java/com/google/cloud/spring/data/firestore/it/UserService.java[tag=user_service]
----

[start=3]
. Make a Spring Bean provider that creates an instance of that class:

[source, java, indent=0]
----
include::{project-root}/spring-cloud-gcp-data-firestore/src/test/java/com/google/cloud/spring/data/firestore/it/FirestoreIntegrationTestsConfiguration.java[tag=user_service_bean]
----

After that, you can autowire your service like so:
[source, java]
----
public class MyApplication {
include::{project-root}/spring-cloud-gcp-data-firestore/src/test/java/com/google/cloud/spring/data/firestore/it/FirestoreRepositoryIntegrationTests.java[tag=autowire_user_service]
}
----

Now when you call the methods annotated with `@Transactional` on your service object, a transaction will be automatically started.
If an error occurs during the execution of a method annotated with `@Transactional`, the transaction will be rolled back. 
If no error occurs, the transaction will be committed.

==== Subcollections
A subcollection is a collection associated with a specific entity.
Documents in subcollections can contain subcollections as well, allowing you to further nest data. You can nest data up to 100 levels deep.

WARNING: Deleting a document does not delete its subcollections!

To use subcollections you will need to create a `FirestoreReactiveOperations` object with a parent entity using `FirestoreReactiveOperations.withParent` call.
You can use this object to save, query and remove entities associated with this parent.
The parent doesn't have to exist in Firestore, but should have a non-empty id field.

Autowire `FirestoreReactiveOperations`:
[source,java,indent=0]
----
@Autowired
FirestoreReactiveOperations firestoreTemplate;
----

Then you can use this object to create a `FirestoreReactiveOperations` object with a custom parent:
[source,java,indent=0]
----
include::{project-root}/spring-cloud-gcp-data-firestore/src/test/java/com/google/cloud/spring/data/firestore/it/FirestoreIntegrationTests.java[tag=subcollection]

----

=== Cloud Firestore Spring Boot Starter

If you prefer using Firestore client only, Spring Cloud GCP provides a convenience starter which automatically configures authentication settings and client objects needed to begin using https://cloud.google.com/firestore/[Google Cloud Firestore] in native mode.

See https://cloud.google.com/firestore/docs/[documentation] to learn more about Cloud Firestore.

To begin using this library, add the `spring-cloud-gcp-starter-firestore` artifact to your project.

Maven coordinates, using <<getting-started.adoc#_bill_of_materials, Spring Cloud GCP BOM>>:

[source,xml]
----
<dependency>
    <groupId>com.google.cloud</groupId>
    <artifactId>spring-cloud-gcp-starter-firestore</artifactId>
</dependency>
----

Gradle coordinates:

[source]
----
dependencies {
  implementation("org.springframework.cloud:spring-cloud-gcp-starter-firestore")
}
----

==== Using Cloud Firestore

The starter automatically configures and registers a `Firestore` bean in the Spring application context. To start using it, simply use the `@Autowired` annotation.

[source,java,indent=0]
----
 @Autowired
 Firestore firestore;

include::{project-root}/spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/firestore/it/FirestoreDocumentationIntegrationTests.java[tag=write]

include::{project-root}/spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/firestore/it/FirestoreDocumentationIntegrationTests.java[tag=read]
----

=== Emulator Usage

The Google Cloud Firebase SDK provides a local, in-memory emulator for Cloud Firestore, which you can use to develop and test your application.

First follow https://firebase.google.com/docs/emulator-suite/install_and_configure[the Firebase emulator installation steps] to install, configure, and run the emulator.

NOTE: By default, the emulator is configured to run on port 8080; you will need to ensure that the emulator does not run on the same port as your Spring application.

Once the Firestore emulator is running, ensure that the following properties are set in your `application.properties` of your Spring application:

----
spring.cloud.gcp.firestore.emulator.enabled=true
spring.cloud.gcp.firestore.host-port=${EMULATOR_HOSTPORT}
----

From this point onward, your application will connect to your locally running emulator instance instead of the real Firestore service.

=== Samples

Spring Cloud GCP provides Firestore sample applications to demonstrate API usage:

- https://github.com/GoogleCloudPlatform/spring-cloud-gcp/tree/master/spring-cloud-gcp-samples/spring-cloud-gcp-data-firestore-sample[Reactive Firestore Repository sample application]:
- https://github.com/GoogleCloudPlatform/spring-cloud-gcp/tree/master/spring-cloud-gcp-samples/spring-cloud-gcp-firestore-sample[Firestore Client Library sample application]
