== Cloud Monitoring

Google Cloud Platform provides a service called https://cloud.google.com/monitoring/[Cloud Monitoring], and https://micrometer.io/docs/registry/stackdriver[Micrometer] can be used with it to easily instrument Spring Boot applications for observability.

Spring Boot already provides auto-configuration for Cloud Monitoring.
This module enables auto-detection of the `project-id` and `credentials`.
Also, it can be customized.

Maven coordinates, using <<getting-started.adoc#_bill_of_materials, Spring Cloud GCP BOM>>:

[source,xml]
----
<dependency>
    <groupId>com.google.cloud</groupId>
    <artifactId>spring-cloud-gcp-starter-metrics</artifactId>
</dependency>
----

Gradle coordinates:

[source,subs="normal"]
----
dependencies {
    implementation("com.google.cloud:spring-cloud-gcp-starter-metrics")
}
----

You must enable Cloud Monitoring API from the Google Cloud Console in order to capture metrics.
Navigate to the https://console.cloud.google.com/apis/api/monitoring.googleapis.com/overview[Cloud Monitoring API] for your project and make sure it’s enabled.

Spring Boot Starter for Cloud Monitoring uses Micrometer.

=== Configuration

All configurations are optional:

|===
| Name | Description | Required | Default value
| `spring.cloud.gcp.metrics.enabled` | Auto-configure Micrometer to send metrics to Cloud Monitoring. | No | `true`
| `spring.cloud.gcp.metrics.project-id` | Overrides the project ID from the <<spring-cloud-gcp-core,Spring Cloud GCP Module>> | No |
| `spring.cloud.gcp.metrics.credentials.location` | Overrides the credentials location from the <<spring-cloud-gcp-core,Spring Cloud GCP Module>> | No |
| `spring.cloud.gcp.metrics.credentials.encoded-key` | Overrides the credentials encoded key from the <<spring-cloud-gcp-core,Spring Cloud GCP Module>> | No |
| `spring.cloud.gcp.metrics.credentials.scopes` | Overrides the credentials scopes from the <<spring-cloud-gcp-core,Spring Cloud GCP Module>> | No |
|===

You can use core Spring Boot Actuator properties to control reporting frequency, etc.
Read https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready-metrics-export-stackdriver[Spring Boot Actuator documentation] for more information on Stackdriver Actuator configurations.

=== Sample

A https://github.com/GoogleCloudPlatform/spring-cloud-gcp/tree/main/spring-cloud-gcp-samples/spring-cloud-gcp-metrics-sample[sample application] is available.
