== Cloud Pub/Sub

Spring Cloud GCP provides an abstraction layer to publish to and subscribe from Google Cloud Pub/Sub topics and to create, list or delete Google Cloud Pub/Sub topics and subscriptions.

A Spring Boot starter is provided to auto-configure the various required Pub/Sub components.

Maven coordinates, using <<getting-started.adoc#_bill_of_materials, Spring Cloud GCP BOM>>:

[source,xml]
----
<dependency>
    <groupId>com.google.cloud</groupId>
    <artifactId>spring-cloud-gcp-starter-pubsub</artifactId>
</dependency>
----

Gradle coordinates:

[source,subs="normal"]
----
dependencies {
    implementation("org.springframework.cloud:spring-cloud-gcp-starter-pubsub")
}
----

This starter is also available from https://start.spring.io[Spring Initializr] through the `GCP Messaging` entry.

[#pubsub-configuration]
=== Configuration

The Spring Boot starter for Google Cloud Pub/Sub provides the following configuration options.

==== Spring Cloud GCP Pub/Sub API Configuration

This section describes options for enabling the integration, specifying the GCP project and credentials, and setting whether the APIs should connect to an emulator for local testing.

|===
| Name | Description | Required | Default value
| `spring.cloud.gcp.pubsub.enabled` | Enables or disables Pub/Sub auto-configuration | No | `true`
| `spring.cloud.gcp.pubsub.project-id` | GCP project ID where the Google Cloud Pub/Sub API is hosted, if different from the one in the <<spring-cloud-gcp-core,Spring Cloud GCP Core Module>>
| No |
| `spring.cloud.gcp.pubsub.credentials.location` | OAuth2 credentials for authenticating with the
Google Cloud Pub/Sub API, if different from the ones in the
<<spring-cloud-gcp-core,Spring Cloud GCP Core Module>> | No |
| `spring.cloud.gcp.pubsub.emulator-host` | The host and port of the local running emulator.
If provided, this will setup the client to connect against a running https://cloud.google.com/pubsub/docs/emulator[Google Cloud Pub/Sub Emulator]. | No |
| `spring.cloud.gcp.pubsub.credentials.encoded-key` | Base64-encoded contents of OAuth2 account private key for authenticating with the
Google Cloud Pub/Sub API, if different from the ones in the
<<spring-cloud-gcp-core,Spring Cloud GCP Core Module>> | No |
| `spring.cloud.gcp.pubsub.credentials.scopes` |
https://developers.google.com/identity/protocols/googlescopes[OAuth2 scope] for Spring Cloud GCP
Pub/Sub credentials | No | https://www.googleapis.com/auth/pubsub
|===

==== Publisher/Subscriber Configuration

This section describes configuration options to customize the behavior of the application's Pub/Sub publishers and subscribers.

|===
| Name | Description | Required | Default value
| `spring.cloud.gcp.pubsub.subscriber.parallel-pull-count` | The number of pull workers | No | 1
| `spring.cloud.gcp.pubsub.subscriber.max-ack-extension-period` | The maximum period a message ack deadline will be extended, in seconds | No | 0
| `spring.cloud.gcp.pubsub.subscriber.pull-endpoint` | The endpoint for synchronous pulling messages | No | pubsub.googleapis.com:443
| `spring.cloud.gcp.pubsub.[subscriber,publisher].executor-threads` | Number of threads used by `Subscriber` instances created by `SubscriberFactory` | No | 4
| `spring.cloud.gcp.pubsub.[subscriber,publisher.batching].flow-control.max-outstanding-element-count`|
Maximum number of outstanding elements to keep in memory before enforcing flow control. | No | unlimited
| `spring.cloud.gcp.pubsub.[subscriber,publisher.batching].flow-control.max-outstanding-request-bytes`|
Maximum number of outstanding bytes to keep in memory before enforcing flow control. | No | unlimited
| `spring.cloud.gcp.pubsub.[subscriber,publisher.batching].flow-control.limit-exceeded-behavior`|
The behavior when the specified limits are exceeded. | No | Block
| `spring.cloud.gcp.pubsub.publisher.batching.element-count-threshold`|
The element count threshold to use for batching. | No | unset (threshold does not apply)
| `spring.cloud.gcp.pubsub.publisher.batching.request-byte-threshold`|
The request byte threshold to use for batching. | No | unset (threshold does not apply)
| `spring.cloud.gcp.pubsub.publisher.batching.delay-threshold-seconds`|
The delay threshold to use for batching.
After this amount of time has elapsed (counting from the first element added), the elements will be wrapped up in a batch and sent. | No | unset (threshold does not apply)
| `spring.cloud.gcp.pubsub.publisher.batching.enabled`|
Enables batching. | No | false
|===

==== GRPC Connection Settings

The Pub/Sub API uses the https://cloud.google.com/pubsub/docs/reference/service_apis_overview#grpc_api[GRPC] protocol to send API requests to the Pub/Sub service.
This section describes configuration options for customizing the GRPC behavior.

NOTE: The properties that refer to `retry` control the RPC retries for transient failures during the gRPC call to Cloud Pub/Sub server.
They do *not* control message redelivery; only message acknowledgement deadline can be used to extend or shorten the amount of time until Pub/Sub attempts redelivery.

|===
| Name | Description | Required | Default value
| `spring.cloud.gcp.pubsub.keepAliveIntervalMinutes` | Determines frequency of keepalive gRPC ping | No | `5 minutes`
| `spring.cloud.gcp.pubsub.[subscriber,publisher].retry.total-timeout-seconds`|
TotalTimeout has ultimate control over how long the logic should keep trying the remote call until it gives up completely.
The higher the total timeout, the more retries can be attempted. | No | 0
| `spring.cloud.gcp.pubsub.[subscriber,publisher].retry.initial-retry-delay-second`|
InitialRetryDelay controls the delay before the first retry.
Subsequent retries will use this value adjusted according to the RetryDelayMultiplier. | No | 0
| `spring.cloud.gcp.pubsub.[subscriber,publisher].retry.retry-delay-multiplier`|
RetryDelayMultiplier controls the change in retry delay.
The retry delay of the previous call is multiplied by the RetryDelayMultiplier to calculate the retry delay for the next call. | No | 1
| `spring.cloud.gcp.pubsub.[subscriber,publisher].retry.max-retry-delay-seconds`|
MaxRetryDelay puts a limit on the value of the retry delay, so that the RetryDelayMultiplier
can't increase the retry delay higher than this amount. | No | 0
| `spring.cloud.gcp.pubsub.[subscriber,publisher].retry.max-attempts`|
MaxAttempts defines the maximum number of attempts to perform.
If this value is greater than 0, and the number of attempts reaches this limit, the logic will give up retrying even if the total retry time is still lower than TotalTimeout. | No | 0
| `spring.cloud.gcp.pubsub.[subscriber,publisher].retry.jittered`|Jitter determines if the delay time should be randomized. | No | true
| `spring.cloud.gcp.pubsub.[subscriber,publisher].retry.initial-rpc-timeout-seconds`|
InitialRpcTimeout controls the timeout for the initial RPC.
Subsequent calls will use this value adjusted according to the RpcTimeoutMultiplier. | No |0
| `spring.cloud.gcp.pubsub.[subscriber,publisher].retry.rpc-timeout-multiplier`|
RpcTimeoutMultiplier controls the change in RPC timeout.
The timeout of the previous call is multiplied by the RpcTimeoutMultiplier to calculate the timeout for the next call. | No | 1
| `spring.cloud.gcp.pubsub.[subscriber,publisher].retry.max-rpc-timeout-seconds`|
MaxRpcTimeout puts a limit on the value of the RPC timeout, so that the RpcTimeoutMultiplier
can't increase the RPC timeout higher than this amount. | No | 0
|===

=== Spring Boot Actuator Support

==== Cloud Pub/Sub Health Indicator

If you are using Spring Boot Actuator, you can take advantage of the Cloud Pub/Sub health indicator called `pubsub`.
The health indicator will verify whether Cloud Pub/Sub is up and accessible by your application.
To enable it, all you need to do is add the https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready[Spring Boot Actuator] to your project.

The `pubsub` indicator will then roll up to the overall application status visible at http://localhost:8080/actuator/health (use the `management.endpoint.health.show-details` property to view per-indicator details).

[source,xml]
----
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-actuator</artifactId>
</dependency>
----

NOTE: If your application already has actuator and Cloud Pub/Sub starters, this health indicator is enabled by default.
To disable the Cloud Pub/Sub indicator, set `management.health.pubsub.enabled` to `false`.

=== Pub/Sub Operations & Template

`PubSubOperations` is an abstraction that allows Spring users to use Google Cloud Pub/Sub without depending on any Google Cloud Pub/Sub API semantics.
It provides the common set of operations needed to interact with Google Cloud Pub/Sub.
`PubSubTemplate` is the default implementation of `PubSubOperations` and it uses the https://github.com/GoogleCloudPlatform/google-cloud-java/tree/master/google-cloud-pubsub[Google Cloud Java Client for Pub/Sub] to interact with Google Cloud Pub/Sub.

==== Publishing to a topic

`PubSubTemplate` provides asynchronous methods to publish messages to a Google Cloud Pub/Sub topic.
The `publish()` method takes in a topic name to post the message to, a payload of a generic type and, optionally, a map with the message headers.
The topic name could either be a canonical topic name within the current project, or the fully-qualified name referring to a topic in a different project using the `projects/<project_name>/topics/<topic_name>` format.

Here is an example of how to publish a message to a Google Cloud Pub/Sub topic:

[source,java,indent=0]
----
include::{project-root}/spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/pubsub/it/PubSubTemplateDocumentationIntegrationTests.java[tag=publish]
----

By default, the `SimplePubSubMessageConverter` is used to convert payloads of type `byte[]`, `ByteString`, `ByteBuffer`, and `String` to Pub/Sub messages.

==== Subscribing to a subscription

Google Cloud Pub/Sub allows many subscriptions to be associated to the same topic.
`PubSubTemplate` allows you to listen to subscriptions via the `subscribe()` method.
When listening to a subscription, messages will be pulled from Google Cloud Pub/Sub asynchronously and passed to a user provided message handler.
The subscription name could either be a canonical subscription name within the current project, or the fully-qualified name referring to a subscription in a different project using the `projects/<project_name>/subscriptions/<subscription_name>` format.

===== Example
Subscribe to a subscription with a message handler:
[source,java,indent=0]
----
include::{project-root}/spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/pubsub/it/PubSubTemplateDocumentationIntegrationTests.java[tag=subscribe]
----
===== Subscribe methods
`PubSubTemplate` provides the following subscribe methods:

[cols="20,80"]
|===
h|subscribe(String subscription, Consumer<BasicAcknowledgeablePubsubMessage> messageConsumer) | asynchronously pulls messages and passes them to `messageConsumer`
h|subscribeAndConvert(String subscription,
 			Consumer<ConvertedBasicAcknowledgeablePubsubMessage<T>> messageConsumer,
 			Class<T> payloadType) | same as `pull`, but converts message payload to `payloadType` using the converter configured in the template
|===

NOTE: As of version 1.2, subscribing by itself is not enough to keep an application running.
For a command-line application, you may want to provide your own `ThreadPoolTaskScheduler` bean named `pubsubSubscriberThreadPool`, which by default creates non-daemon threads that will keep an application from stopping.
This default behavior has been overridden in Spring Cloud GCP for consistency with Cloud Pub/Sub client library, and to avoid holding up command-line applications that would like to shut down once their work is done.

==== Pulling messages from a subscription

Google Cloud Pub/Sub supports synchronous pulling of messages from a subscription.
This is different from subscribing to a subscription, in the sense that subscribing is an asynchronous task.

===== Example
Pull up to 10 messages:
[source,java,indent=0]
----
include::{project-root}/spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/pubsub/it/PubSubTemplateDocumentationIntegrationTests.java[tag=pull]
----

===== Pull methods

`PubsubTemplate` provides the following pull methods:
[cols="20,80"]
|===
h|pull(String subscription, Integer maxMessages,
       			Boolean returnImmediately) | Pulls a number of messages from a subscription, allowing for the retry settings to be configured.
       			Any messages received by `pull()` are not automatically acknowledged. See <<Acknowledging messages>>.

				The `maxMessages` parameter is the maximum limit of how many messages to pull from a subscription in a single call; this value **must** be greater than 0.
				You may omit this parameter by passing in `null`; this means there will be no limit on the number of messages pulled (`maxMessages` will be `Integer.MAX_INTEGER`).

       			If `returnImmediately` is `true`, the system will respond immediately even if it there are no messages available to return in the `Pull` response. Otherwise, the system may wait (for a bounded amount of time) until at least one message is available, rather than returning no messages.
h|pullAndAck | Works the same as the `pull` method and, additionally, acknowledges all received messages.

h|pullNext | Allows for a single message to be pulled and automatically acknowledged from a subscription.

h|pullAndConvert | Works the same as the `pull` method and, additionally, converts the Pub/Sub binary payload to an object of the desired type, using the converter configured in the template.
|===

===== Acknowledging messages

There are two ways to acknowledge messages.

. To acknowledge multiple messages at once, you can use the `PubSubTemplate.ack()` method.
You can also use the `PubSubTemplate.nack()` for negatively acknowledging messages.
Using these methods for acknowledging messages in batches is more efficient than acknowledging messages individually, but they *require* the collection of messages to be from the same project.

. To acknowledge messages individually you can use the `ack()` or `nack()` method on each of them (to acknowledge or negatively acknowledge, correspondingly).

NOTE: All `ack()`, `nack()`, and `modifyAckDeadline()` methods on messages, as well as `PubSubSubscriberTemplate`, are implemented asynchronously, returning a `ListenableFuture<Void>` to enable asynchronous processing.

==== JSON support

For serialization and deserialization of POJOs using Jackson JSON, configure a `PubSubMessageConverter` bean, and the Spring Boot starter for GCP Pub/Sub will automatically wire it into the `PubSubTemplate`.

[source,java,indent=0]
----
include::{project-root}/spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/pubsub/it/PubSubTemplateDocumentationIntegrationTests.java[tag=json_bean]
----

NOTE: Alternatively, you can set it directly by calling the `setMessageConverter()` method on the `PubSubTemplate`.
Other implementations of the `PubSubMessageConverter` can also be configured in the same manner.

Assuming you have the following class defined:

[source,java,indent=0]
----
include::{project-root}/spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/pubsub/it/PubSubTemplateDocumentationIntegrationTests.java[tag=json_convertible_class]
----

You can serialize objects to JSON on publish automatically:

[source,java,indent=0]
----
include::{project-root}/spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/pubsub/it/PubSubTemplateDocumentationIntegrationTests.java[tag=json_publish]
----

And that's how you convert messages to objects on pull:
[source,java,indent=0]
----
include::{project-root}/spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/pubsub/it/PubSubTemplateDocumentationIntegrationTests.java[tag=json_pull]
----


Please refer to our https://github.com/GoogleCloudPlatform/spring-cloud-gcp/tree/master/spring-cloud-gcp-samples/spring-cloud-gcp-integration-pubsub-json-sample[Pub/Sub JSON Payload Sample App] as a reference for using this functionality.

=== Reactive Stream Subscription

It is also possible to acquire a reactive stream backed by a subscription.
To do so, a Project Reactor dependency (`io.projectreactor:reactor-core`) must be added to the project.
The combination of the Pub/Sub starter and the Project Reactor dependencies will then make a `PubSubReactiveFactory` bean available, which can then be used to get a `Publisher`.

[source,java]
----
@Autowired
PubSubReactiveFactory reactiveFactory;

// ...

Flux<AcknowledgeablePubsubMessage> flux
				= reactiveFactory.poll("exampleSubscription", 1000);
----

The `Flux` then represents an infinite stream of GCP Pub/Sub messages coming in through the specified subscription.
For unlimited demand, the Pub/Sub subscription will be polled regularly, at intervals determined by `pollingPeriodMs` parameter passed in when creating the `Flux`.
For bounded demand, the `pollingPeriodMs` parameter is unused.
Instead, as many messages as possible (up to the requested number) are delivered immediately, with the remaining messages delivered as they become available.

Any exceptions thrown by the underlying message retrieval logic will be passed as an error to the stream.
The error handling operators (`Flux#retry()`, `Flux#onErrorResume()` etc.) can be used to recover.

The full range of Project Reactor operations can be applied to the stream.
For example, if you only want to fetch 5 messages, you can use `limitRequest` operation to turn the infinite stream into a finite one:

[source,java]
----
Flux<AcknowledgeablePubsubMessage> fiveMessageFlux = flux.limitRequest(5);
----

Messages flowing through the `Flux` should be manually acknowledged.

[source,java]
----
flux.doOnNext(AcknowledgeablePubsubMessage::ack);
----

=== Pub/Sub management

`PubSubAdmin` is the abstraction provided by Spring Cloud GCP to manage Google Cloud Pub/Sub resources.
It allows for the creation, deletion and listing of topics and subscriptions.

NOTE: Generally when referring to topics and subscriptions, you can either use the short canonical name within the current project, or the fully-qualified name referring to a topic or subscription in a different project using the `projects/<project_name>/(topics|subscriptions)/<name>` format.

`PubSubAdmin` depends on `GcpProjectIdProvider` and either a `CredentialsProvider` or a `TopicAdminClient` and a `SubscriptionAdminClient`.
If given a `CredentialsProvider`, it creates a `TopicAdminClient` and a `SubscriptionAdminClient` with the Google Cloud Java Library for Pub/Sub default settings.
The Spring Boot starter for GCP Pub/Sub auto-configures a `PubSubAdmin` object using the `GcpProjectIdProvider` and the `CredentialsProvider` auto-configured by the Spring Boot GCP Core starter.

==== Creating a topic

`PubSubAdmin` implements a method to create topics:

[source,java]
----
public Topic createTopic(String topicName)
----

Here is an example of how to create a Google Cloud Pub/Sub topic:

[source,java]
----
public void newTopic() {
    pubSubAdmin.createTopic("topicName");
}
----

==== Deleting a topic

`PubSubAdmin` implements a method to delete topics:

[source,java]
----
public void deleteTopic(String topicName)
----

Here is an example of how to delete a Google Cloud Pub/Sub topic:

[source,java]
----
public void deleteTopic() {
    pubSubAdmin.deleteTopic("topicName");
}
----

==== Listing topics

`PubSubAdmin` implements a method to list topics:

[source,java]
----
public List<Topic> listTopics
----

Here is an example of how to list every Google Cloud Pub/Sub topic name in a project:

[source,java,indent=0]
----
include::{project-root}/spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/pubsub/it/PubSubTemplateDocumentationIntegrationTests.java[tag=list_topics]
----

==== Creating a subscription

`PubSubAdmin` implements a method to create subscriptions to existing topics:

[source,java]
----
public Subscription createSubscription(String subscriptionName, String topicName, Integer ackDeadline, String pushEndpoint)
----

Here is an example of how to create a Google Cloud Pub/Sub subscription:

[source,java]
----
public void newSubscription() {
    pubSubAdmin.createSubscription("subscriptionName", "topicName", 10, “https://my.endpoint/push”);
}
----

Alternative methods with default settings are provided for ease of use.
The default value for `ackDeadline` is 10 seconds.
If `pushEndpoint` isn’t specified, the subscription uses message pulling, instead.

[source,java]
----
public Subscription createSubscription(String subscriptionName, String topicName)
----

[source,java]
----
public Subscription createSubscription(String subscriptionName, String topicName, Integer ackDeadline)
----

[source,java]
----
public Subscription createSubscription(String subscriptionName, String topicName, String pushEndpoint)
----

==== Deleting a subscription

`PubSubAdmin` implements a method to delete subscriptions:

[source,java]
----
public void deleteSubscription(String subscriptionName)
----

Here is an example of how to delete a Google Cloud Pub/Sub subscription:

[source,java]
----
public void deleteSubscription() {
    pubSubAdmin.deleteSubscription("subscriptionName");
}
----

==== Listing subscriptions

`PubSubAdmin` implements a method to list subscriptions:

[source,java]
----
public List<Subscription> listSubscriptions()
----

Here is an example of how to list every subscription name in a project:

[source,java,indent=0]
----
include::{project-root}/spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/pubsub/it/PubSubTemplateDocumentationIntegrationTests.java[tag=list_subscriptions]
----

=== Sample

Sample applications for https://github.com/GoogleCloudPlatform/spring-cloud-gcp/tree/master/spring-cloud-gcp-samples/spring-cloud-gcp-pubsub-sample[using the template] and https://github.com/GoogleCloudPlatform/spring-cloud-gcp/tree/master/spring-cloud-gcp-samples/spring-cloud-gcp-pubsub-reactive-sample[using a subscription-backed reactive stream] are available.
