:spring-security-ref: https://docs.spring.io/spring-security/site/docs/current/reference/htmlsingle/
:spring-security-javadoc: https://docs.spring.io/spring-security/site/docs/current/api/org/springframework/security/

== Cloud Identity-Aware Proxy (IAP) Authentication

https://cloud.google.com/iap/[Cloud Identity-Aware Proxy (IAP)] provides a security layer over applications deployed to Google Cloud.

The IAP starter uses {spring-security-ref}#oauth2resourceserver[Spring Security OAuth 2.0 Resource Server] functionality to automatically extract user identity from the proxy-injected `x-goog-iap-jwt-assertion` HTTP header.

The following claims are validated automatically:

 * Issue time
 * Expiration time
 * Issuer
 * Audience

The _audience_ (`"aud"` claim) validation string is automatically determined when the application is running on App Engine Standard or App Engine Flexible.
This functionality relies on Cloud Resource Manager API to retrieve project details, so the following setup is needed:

* Enable Cloud Resource Manager API in https://console.developers.google.com/apis/api/cloudresourcemanager.googleapis.com[GCP Console].
* Make sure your application has `resourcemanager.projects.get` permission.

App Engine automatic _audience_ determination can be overridden by using `spring.cloud.gcp.security.iap.audience` property. It supports multiple allowable audiences by providing a comma-delimited list.

For Compute Engine or Kubernetes Engine `spring.cloud.gcp.security.iap.audience` property *must* be provided, as the _audience_ string depends on the specific Backend Services setup and cannot be inferred automatically.
To determine the _audience_ value, follow directions in IAP https://cloud.google.com/iap/docs/signed-headers-howto#verify_the_jwt_payload[Verify the JWT payload] guide.
If `spring.cloud.gcp.security.iap.audience` is not provided, the application will fail to start the following message:

```
No qualifying bean of type 'org.springframework.cloud.gcp.security.iap.AudienceProvider' available.
```

NOTE: If you create a custom {spring-security-javadoc}config/annotation/web/configuration/WebSecurityConfigurerAdapter.html[`WebSecurityConfigurerAdapter`], enable extracting user identity by adding `.oauth2ResourceServer().jwt()` configuration to the {spring-security-javadoc}config/annotation/web/builders/HttpSecurity.html[`HttpSecurity`] object.
 If no custom {spring-security-javadoc}config/annotation/web/configuration/WebSecurityConfigurerAdapter.html[`WebSecurityConfigurerAdapter`] is present, nothing needs to be done because Spring Boot will add this customization by default.

Starter Maven coordinates, using <<getting-started.adoc#_bill_of_materials, Spring Cloud GCP BOM>>:

[source,xml]
----
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-gcp-starter-security-iap</artifactId>
</dependency>
----

Starter Gradle coordinates:

[source]
----
dependencies {
    compile group: 'org.springframework.cloud', name: 'spring-cloud-gcp-starter-security-iap'
}
----

=== Configuration
The following properties are available.

CAUTION: Modifying registry, algorithm, and header properties might be useful for testing, but the defaults should not be changed in production.

|====================================================
|Name |Description |Required |Default

|`spring.cloud.gcp.security.iap.registry`
|Link to JWK public key registry.
|true
|`https://www.gstatic.com/iap/verify/public_key-jwk`

|`spring.cloud.gcp.security.iap.algorithm`
|Encryption algorithm used to sign the JWK token.
|true
|`ES256`

|`spring.cloud.gcp.security.iap.header`
|Header from which to extract the JWK key.
|true
|`x-goog-iap-jwt-assertion`

|`spring.cloud.gcp.security.iap.issuer`
|JWK issuer to verify.
|true
|`https://cloud.google.com/iap`

|`spring.cloud.gcp.security.iap.audience`
|Custom JWK audience to verify.
|false on App Engine; true on GCE/GKE
|

|====================================================

=== Sample

A https://github.com/spring-cloud/spring-cloud-gcp/tree/master/spring-cloud-gcp-samples/spring-cloud-gcp-security-iap-sample[sample application] is available.
