== Spring Data

http://projects.spring.io/spring-data/[Spring Data]
is an abstraction for storing and retrieving POJOs in numerous storage technologies.
Spring Cloud GCP adds Spring Data support for Google Cloud Spanner.

A Spring Boot starter is provided to auto-configure the various Storage components.

Maven coordinates for the Spring Boot Starter for Spanner, using Spring Cloud GCP BOM:

[source,xml]
----
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-gcp-starter-data-spanner</artifactId>
</dependency>
----

Gradle coordinates:

[source,subs="normal"]
----
dependencies {
    compile group: 'org.springframework.cloud', name: 'spring-cloud-gcp-starter-data-spanner'
}
----

This setup takes care of bringing in the latest compatible version of Cloud Java Spanner libraries as well.

== Spring Data Spanner


=== Configuration

To setup Spring Data Spanner, you have to configure connection to Cloud Spanner and Repositories (if you want to use them).

==== Spanner settings

You will need to use link:../spring-cloud-gcp-starters/spring-cloud-gcp-starter-data-spanner[Spring Boot Starter for Spring Data Spanner] to configure Google Cloud Spanner in your Spring application. It contains all the necessary setup that makes it easy to authenticate with your Google Cloud project.
The following configuration options are available:

|===
| Name | Description | Optional | Default value
| `spring.cloud.gcp.spanner.projectId` | the GCP project ID to use | Yes | provided by Spring Cloud GCP
| `spring.cloud.gcp.spanner.instanceId` | Spanner instance to use | No |
| `spring.cloud.gcp.spanner.database` |
Spanner database to use | No |
|===

==== Repository settings

Spring Data Repositories (see below for functionality) can be configured via the `@EnableSpannerRepositories` annotation on your main configuration file (typically the `@SpringBootApplication` file.

=== Mapping POJO domain objects to Spanner tables using annotations

Spring Data Spanner allows you to map POJOs to Spanner tables:

[source,java]
----
@Table(name = "students")
public class SimpleStudent {
	@PrimaryKeyColumn(keyOrder = 1)
	String id;

	@Column(name = "first_name")
	String name;

	@ColumnInnerType(innerType = String.class)
	List<String> teachers;

	int age;
}
----

- `@Table` provides the name of the Spanner table that stores instances of this class, one per row.
- `@PrimaryKeyColumn` annotation is required and identifies the properties corresponding to the primary key columns in
order starting with 1 and increasing consecutively.
- The `@Column` annotation optionally provides a different column name than that of the property.
- Spanner supports `List` types as fields, the `@ColumnInnerType` annotation is required for `List` properties due to Java's type erasure.

=== Template API

`SpannerOperations` and its implementation, `SpannerTemplate` provides the XYZTemplate pattern familiar for Spring developers and as such provides:
 - resource management
 - one stop shop to Spanner operations with the Spring Data POJO mapping and conversion features
 - exception conversion

After your setup with Spring Boot Starter, you can configure a template simply by adding a member of the `SpannerOperations` interface to your class:

[source,java]
----
`@Autowire`
SpannerOperations



----

=== Supported Types

Spring Data Spanner supports the following types for regular fields:

* `com.google.cloud.ByteArray`
* `com.google.cloud.Date`
* `com.google.cloud.Timestamp`
* `java.lang.Boolean`
* `java.lang.Long`
* `java.lang.String`
* `double[]`
* `long[]`
* `boolean[]`

Spring Data Spanner supports the following inner types for `List` fields:

* `com.google.cloud.ByteArray`
* `com.google.cloud.Date`
* `com.google.cloud.Timestamp`
* `java.lang.Boolean`
* `java.lang.Long`
* `java.lang.String`


[source,java]
----
public interface StudentRepository extends SpannerRepository<SimpleStudent> {

	List<SimpleStudent> findTop3DistinctByIdAndNameOrAgeOrderByAgeDesc(
			String id, String name, int age);

	int countByAgeLessThanEqual(int age);

	// This method uses the query from the properties file instead of one generated based on name.
	List<SimpleStudent> fetchBySomeQuery(String someArg);
}

----

These can be used in an application like this:

[source,java]
----
@EnableSpannerRepositories(namedQueriesLocation = "classpath:/spanner-named-queries.properties")
public class MyApplication {

	@Autowired
	SpannerOperations spannerOperations;

	@Autowired
	StudentRepository studentRepository;

	public void demo() {

	  // storing new students
	  SimpleStudent ss = new SimpleStudent();
	  ss.name = "student1";
	  ss.age = 99;
	  spannerOperations.insert(ss);

	  // getting students from Spanner
	  List<SimpleStudent> ssList =
	    studentRepository.findTop3DistinctByIdAndNameOrAgeOrderByAgeDesc("someId", "bob", 12);

	  List<SimpleStudent> ssList2 = studentRepository.fetchBySomeQuery("some argument");
	}
}

----

The https://docs.spring.io/spring-data/commons/docs/current/reference/html/#repositories.query-methods[query methods]
in the `StudentRepository` are generated based on the convention of their names
except for `fetchBySomeQuery`, which is defined in the `spanner-named-queries.properties` file
like `SimpleStudent.fetchBySomeQuery=SELECT * FROM students WHERE name = @someArg`.

When defining `StudentRepository`, it is important to note that it extends the
`PagingAndSortingRepository`, which is supported by Spring Cloud GCP Data Spanner. The first type
argument refers to the underlying entity, and the second type parameter refers to the `@Id` type
of that entity. Id types must correspond to one of the https://cloud.google.com/spanner/docs/data-types[supported primary key types in Spanner].
