:spring-data-commons-ref: https://docs.spring.io/spring-data/data-commons/docs/current/reference/html

== Spring Data Spanner

http://projects.spring.io/spring-data/[Spring Data]
is an abstraction for storing and retrieving POJOs in numerous storage technologies.
Spring Cloud GCP adds Spring Data support for http://cloud.google.com/spanner/[Google Cloud
Spanner].

A Spring Boot starter is provided to auto-configure the various Storage components.

Maven coordinates for the Spring Boot Starter for Spanner, using Spring Cloud GCP BOM:

[source,xml]
----
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-gcp-starter-data-spanner</artifactId>
</dependency>
----

Gradle coordinates:

[source,subs="normal"]
----
dependencies {
    compile group: 'org.springframework.cloud', name: 'spring-cloud-gcp-starter-data-spanner'
}
----

This setup takes care of bringing in the latest compatible version of Cloud Java Spanner libraries
as well.


=== Configuration

To setup Spring Data Spanner, you have to configure the following:

* Setup the connection details to Google Cloud Spanner.
* Enable Spring Data Repositories (optional).

==== Spanner settings

You can the use link:../spring-cloud-gcp-starters/spring-cloud-gcp-starter-data-spanner[Spring Boot
Starter for Spring Data Spanner] to autoconfigure Google Cloud Spanner in your Spring application.
It contains all the necessary setup that makes it easy to authenticate with your Google Cloud
project.
The following configuration options are available:

|===
| Name | Description | Optional | Default value
| `spring.cloud.gcp.spanner.instance-id` | Spanner instance to use | No |
| `spring.cloud.gcp.spanner.database` |
Spanner database to use | No |
| `spring.cloud.gcp.spanner.project-id` | GCP project ID where the Google Cloud Spanner API
is hosted, if different from the one in the <<spring-cloud-gcp-core,Spring Cloud GCP Core Module>>
| Yes |
| `spring.cloud.gcp.spanner.credentials.location` | OAuth2 credentials for authenticating with the
Google Cloud Spanner API, if different from the ones in the
<<spring-cloud-gcp-core,Spring Cloud GCP Core Module>> | Yes |
| `spring.cloud.gcp.spanner.credentials.scopes` |
https://developers.google.com/identity/protocols/googlescopes[OAuth2 scope] for Spring Cloud GCP
Spanner credentials | Yes | https://www.googleapis.com/auth/spanner.data
|===

==== Repository settings

Spring Data Repositories can be configured via the `@EnableSpannerRepositories` annotation on your
main `@Configuration` class.
With our Spring Boot Starter for Spring Data Spanner, `@EnableSpannerRepositories` is automatically
added.
It is not required to add it to any other class, unless there is a need to override finer
grain configuration parameters provided by
https://github.com/spring-cloud/spring-cloud-gcp/blob/master/spring-cloud-gcp-data-spanner/src/main/java/org/springframework/cloud/gcp/data/spanner/repository/config/EnableSpannerRepositories.java[`@EnableSpannerRepositories`].

==== Autoconfiguration

Our Spring Boot autoconfiguration creates the following beans available in the Spring application
context:

- an instance of `SpannerTemplate`
- an instance of all user defined repositories extending `SpannerRepository`, when repositories
are enabled
- an instance of `DatabaseClient` from the Google Cloud Java Client for Spanner, for convenience and
lower level API access


=== Mapping POJO domain objects to Spanner tables using annotations

Spring Data Spanner allows you to map POJOs to Spanner tables:

[source,java]
----
@Table(name = "trades")
public class Trade {

	@PrimaryKeyColumn(keyOrder = 2)
	String action;

	Double price;

	Double shares;

	@PrimaryKeyColumn(keyOrder = 1)
	String symbol;

	@Column(name = "trader_id")
	String traderId;

	@ColumnInnerType(innerType = Double.class)
	List<Double> curve;
}
----

- `@Table` provides the name of the Spanner table that stores instances of this class, one per row.
- `@PrimaryKeyColumn` annotation is required and identifies the properties corresponding to the
primary key columns in order, starting with 1 and increasing consecutively.
- The `@Column` annotation optionally provides a different column name than that of the property.
- Spanner supports `List` types as fields, the `@ColumnInnerType` annotation is required for `List`
properties due to Java's type erasure.

#### SpEL expressions for table names

In some cases, you might want the `@Table` table name to be determined dynamically.
To do that, you can use
https://docs.spring.io/spring/docs/current/spring-framework-reference/core.html#expressions[Spring
Expression Language].

For example:

[source, java]
----

@Table(name = "trades_#{tableNameSuffix}")
public class Trade {
	// ...
}
----

The table name will be resolved only if the `tableNameSuffix` value/bean in the Spring application
context is defined.
For example, if `tableNameSuffix` has the value "123", the table name will resolve to `trades_123`.

=== Template API

`SpannerOperations` and its implementation, `SpannerTemplate`, provides the Template pattern
familiar to Spring developers.
It provides:

 - Resource management
 - One-stop-shop to Spanner operations with the Spring Data POJO mapping and conversion features
 - Exception conversion

Using the `autoconfigure` provided by our Spring Boot Starter for Spanner, your Spring application
context will contain a fully configured `SpannerTemplate` object that you can easily autowire in
your application:

[source,java]
----
@SpringBootApplication
public class SpannerTemplateExample {

	@Autowired
	SpannerOperations spannerTemplate;

	public void doSomething() {
		this.spannerOperations.delete(Trade.class, KeySet.all());
		//...
		Trade t = new Trade();
		//...
		this.spannerOperations.insert(t);
		//...
		List<Trade> tradesByAction = spannerOperations.findAll(Trade.class);
		//...
	}
}
----

The Template API provides convenience methods for:

- https://cloud.google.com/spanner/docs/reads[Reads], and by providing SpannerReadOptions and
SpannerQueryOptions
   ** Stale read
   ** Read with secondary indices
   ** Read with limits and flow control
- https://cloud.google.com/spanner/docs/reads#execute_a_query[Queries]
- DML operations (delete, insert, update, upsert)
- Partial reads
   ** You can define a set of columns to be read into your entity
- Partial writes
   ** Persist only a few properties from your entity
- Read-only transactions
- Locking read-write transactions


=== Supported Types

Spring Data Spanner supports the following types for regular fields:

* `com.google.cloud.ByteArray`
* `com.google.cloud.Date`
* `com.google.cloud.Timestamp`
* `java.lang.Boolean`, `boolean`
* `java.lang.Long`, `long`
* `java.lang.Integer`, `int`
* `java.lang.String`
* `double[]`
* `long[]`
* `boolean[]`
* `java.util.Date`
* `java.util.Instant`
* `java.sql.Date`


For `ARRAY` Spanner types, you'll need to use `List` in the fields. For the inner type of a `List`
field, Spring Data Spanner supports the following inner types:

* `com.google.cloud.ByteArray`
* `com.google.cloud.Date`
* `com.google.cloud.Timestamp`
* `java.lang.Boolean`, `boolean`
* `java.lang.Long`, `long`
* `java.lang.Integer`, `int`
* `java.lang.String`
* `java.util.Date`
* `java.util.Instant`
* `java.sql.Date`

=== Custom type conversions

Custom converters can be used extending the type support for user defined types.

. Converters need to implement the `org.springframework.core.convert.converter.Converter` interface
both directions.
. The user defined type needs to be mapped to one the basic types supported by Spanner:

* `com.google.cloud.ByteArray`
* `com.google.cloud.Date`
* `com.google.cloud.Timestamp`
* `java.lang.Boolean`, `boolean`
* `java.lang.Long`, `long`
* `java.lang.String`
* `double[]`
* `long[]`
* `boolean[]`

. An instance of both Converters needs to be passed to a `MappingSpannerConverter`, which then has
to be made available as a `@Bean` for `SpannerConverter`.

For example:

We would like to have a field of type `Person` on our `Trade` POJO:
[source, java]
----

@Table(name = "trades")
public class Trade {
  //...
  Person person;
  //...
}
----

Where Person is a simple class:

[source, java]
----
public class Person {

  public String firstName;
  public String lastName;

}
----

We have to define the two converters:

[source, java]
----
  public class PersonWriteConverter implements Converter<Person, String> {

    @Override
    public String convert(Person person) {
      return person.firstName + " " + person.lastName;
    }
  }

  public class PersonReadConverter implements Converter<String, Person> {

    @Override
    public Person convert(String s) {
      Person person = new Person();
      person.firstName = s.split(" ")[0];
      person.lastName = s.split(" ")[1];
      return person;
    }
  }
----

That will be configured in our `@Configuration` file:

[source, java]
----
@Configuration
public class ConverterConfiguration {

	@Bean
	public SpannerConverter spannerConverter(SpannerMappingContext spannerMappingContext) {
		return new MappingSpannerConverter(spannerMappingContext,
				Arrays.asList(new PersonWriteConverter()),
				Arrays.asList(new PersonReadConverter()));
	}
}
----


=== Repositories

{spring-data-commons-ref}/#repositories[Spring Data Repositories] are a powerful abstraction that
can save you a lot of boilerplate code.

For example:

[source,java]
----
public interface TradeRepository extends PagingAndSortingRepository<Trade, String> {

	List<Trade> findByAction(String action);

	int countByAction(String action);

	// Named methods are powerful, but can get unwieldy
	List<Trade> findTop3DistinctByActionAndSymbolOrTraderIdOrderBySymbolDesc(
  			String action, String symbol, String traderId);

	// This method uses the query from the properties file instead of one generated based on name.
	List<Trade> fetchByActionNamedQuery(String action);

}
----

Spring Data generates a working implementation of the specified interface, which can be conveniently
autowired into an application.

[source,java]
----
public class MyApplication {

	@Autowired
	SpannerOperations spannerOperations;

	@Autowired
	StudentRepository studentRepository;

	public void demo() {

		this.tradeRepository.deleteAll(); //defined on CrudRepository
		String traderId = "demo_trader";
		Trade t = new Trade();
		t.symbol = stock;
		t.action = action;
		t.traderId = traderId;
		t.price = 100.0;
		t.shares = 12345.6;
		this.spannerOperations.insert(t); //defined on CrudRepository

		Iterable<Trade> allTrades = this.tradeRepository.findAll(); //defined on CrudRepository

		int count = this.tradeRepository.countByAction("BUY");

	}
}

----

=== Query methods


==== Resolving methods by name

In the example above, the {spring-data-commons-ref}/#repositories.query-methods[query methods]
in `TradeRepository` are generated based on the name of the methods, using the
{spring-data-commons-ref}#repositories.query-methods.query-creation[Spring Data Query creation
naming convention].

`List<Trade> findByAction(String action)` would translate to a `SELECT * FROM trades WHERE action = ?`.

The function `List<Trade> findTop3DistinctByActionAndSymbolOrTraderIdOrderBySymbolDesc(String action, String symbol, String traderId);` will be translated as the equivalent of this SQL query:

[source, sql]
----
SELECT DISTINCT * FROM trades
WHERE ACTION = ? AND SYMBOL = ? AND Or TRADER_ID = ?
ORDER BY SYMBOL DESC
LIMIT 3
----

==== Mapping SQL to repository methods


The example above for `List<Trade> fetchByActionNamedQuery(String action)` does not match the
{spring-data-commons-ref}#repositories.query-methods.query-creation[Spring Data Query creation
naming convention], so we have to map a parametrized Spanner SQL query to it.

The SQL query for the method can be mapped to repository methods in one of two ways:

 * `namedQueries` properties file
 * using the `@Query` annotation

By default, the `namedQueriesLocation` attribute on `@EnableSpannerRepositories` points to the
`META-INF/spanner-named-queries.properties` file.
You can specify the query for a method in the properties file by providing the SQL as the value for
the "interface.method" property:

[source, properties]
----
Trade.fetchByActionNamedQuery=SELECT * FROM trades WHERE trades.action = @tag0`
----

Using the `@Query` annotation:

[source, java]
----
  @Query("SELECT * FROM trades WHERE trades.action = @tag0")
  List<Trade> fetchByActionNamedQuery(String action);
----

Table names can be used directly.
For example, "trades" in the above example.
Alternatively, table names can be resolved from the `@Table` annotation on domain classes as well.
In this case, the query should refer to table names with fully qualified class names between `:`
characters: `:fully.qualified.ClassName:`.
A full example would look like:

[source, java]
----
  @Query("SELECT * FROM :com.example.Trade: WHERE trades.action = @tag0")
  List<Trade> fetchByActionNamedQuery(String action);
----
