[[spring-cloud-gcp-reference]]
= Spring Cloud GCP
João André Martins; Jisha Abubaker; Ray Tsang; Mike Eltsufin; Artem Bilan; Andreas Berger; Balint Pato; Chengyuan Zhao; Dmitry Solomakha; Elena Felder; Daniel Zou, Eddú Meléndez

include::_attributes.adoc[]

== Introduction

The Spring Cloud GCP project makes the Spring Framework a first-class citizen of Google Cloud Platform (GCP).

Spring Cloud GCP lets you leverage the power and simplicity of the Spring Framework to:

- Publish and subscribe to Google Cloud Pub/Sub topics
- Configure Spring JDBC with a few properties to use Google Cloud SQL
- Map objects, relationships, and collections with Spring Data Cloud Spanner, Spring Data Cloud Datastore and Spring Data Reactive Repositories for Cloud Firestore
- Write and read from Spring Resources backed up by Google Cloud Storage
- Exchange messages with Spring Integration using Google Cloud Pub/Sub on the background
- Trace the execution of your app with Spring Cloud Sleuth and Google Stackdriver Trace
- Configure your app with Spring Cloud Config, backed up by the Google Runtime Configuration API
- Consume and produce Google Cloud Storage data via Spring Integration GCS Channel Adapters
- Use Spring Security via Google Cloud IAP
- Analyze your images for text, objects, and other content with Google Cloud Vision

include::getting-started.adoc[]

include::core.adoc[]

include::storage.adoc[]

include::sql.adoc[]

include::pubsub.adoc[]

include::spring-integration.adoc[]

include::spring-stream.adoc[]

include::spring-cloud-bus-pubsub.adoc[]

include::trace.adoc[]

include::logging.adoc[]

include::metrics.adoc[]

include::spanner.adoc[]

include::datastore.adoc[]

include::firestore.adoc[]

include::memorystore.adoc[]

include::bigquery.adoc[]

include::security-iap.adoc[]

include::vision.adoc[]

include::secretmanager.adoc[]

include::config.adoc[]

include::cloudfoundry.adoc[]

include::kotlin.adoc[]

== Configuration properties

To see the list of all GCP related configuration properties please check link:appendix.html[the Appendix page].
