[[spring-cloud-gcp-reference]]
= Spring Cloud GCP
João André Martins; Jisha Abubaker; Ray Tsang; Mike Eltsufin; Artem Bilan; Andreas Berger; Balint Pato; Chengyuan Zhao; Dmitry Solomakha; Elena Felder; Daniel Zou

:doctype: book
:toc:
:toclevels: 4
:source-highlighter: prettify
:numbered:

== Introduction

The Spring Cloud GCP project makes the Spring Framework a first-class citizen of Google Cloud Platform (GCP).

Spring Cloud GCP lets you leverage the power and simplicity of the Spring Framework to:

. Analyze your images for text, objects, and other content with Google Cloud Vision
. Use Spring Security via Google Cloud IAP
. Map objects, relationships, and collections with Spring Data Cloud Spanner and Spring Data Cloud Datastore
. Publish and subscribe to Google Cloud Pub/Sub topics
. Configure Spring JDBC with a few properties to use Google Cloud SQL
. Write and read from Spring Resources backed up by Google Cloud Storage
. Exchange messages with Spring Integration using Google Cloud Pub/Sub on the background
. Trace the execution of your app with Spring Cloud Sleuth and Google Stackdriver Trace
. Configure your app with Spring Cloud Config, backed up by the Google Runtime Configuration API
. Consume and produce Google Cloud Storage data via Spring Integration GCS Channel Adapters

include::dependency-management.adoc[]

include::getting-started.adoc[]

include::core.adoc[]

include::pubsub.adoc[]

include::storage.adoc[]

include::sql.adoc[]

include::spring-integration.adoc[]

include::spring-stream.adoc[]

include::trace.adoc[]

include::logging.adoc[]

include::config.adoc[]

include::spanner.adoc[]

include::datastore.adoc[]

include::memorystore.adoc[]

include::security-iap.adoc[]

include::vision.adoc[]

include::cloudfoundry.adoc[]

include::kotlin.adoc[]
