== Emulators support
Our tools simplify starting and stopping Cloud PubSub and Cloud Spanner emulators when you test your application.

In order to use it, you need to add this dependency into your `pom.xml` file:

[source,xml]
----
<dependency>
	<groupId>org.springframework.cloud</groupId>
	<artifactId>spring-cloud-gcp-test</artifactId>
	<scope>test</scope>
</dependency>
----

Also, you need to have `gcloud` and the emulators installed and configured, as described later.

=== Cloud PubSub Emulator
In order to use our Cloud PubSub Emulator helper tools, you would need to install the emulator first.
Follow the https://cloud.google.com/pubsub/docs/emulator[installation instructions].

==== JUnit 4 Class Rule
The rule starts the emulator process before the tests run and kills it afterwards.
You just need to add a rule into your test class to enable it.

[source,java]
----
import org.springframework.cloud.gcp.test.PubSubEmulatorRule;

public class PubSubTests {
	@ClassRule
	public static PubSubEmulatorRule emulator = new PubSubEmulatorRule();

		//your tests
}
----

==== Utility class
If you prefer controlling the emulator manually, you can use PubSubEmulatorHelper.

[source,java]
----
	PubSubEmulatorHelper emulatorHelper = new PubSubEmulatorHelper();

	emulatorHelper.startEmulator();

	//your code

	emulatorHelper.shutdownEmulator();
----

=== Cloud Spanner Emulator
In order to use our Cloud Spanner Emulator helper tools, you would need to install the emulator first.
Follow the https://cloud.google.com/spanner/docs/emulator[installation instructions].
Make sure you create an emulator configuration and call it `emulator`.

==== Spring Configuration
If you are testing your Spring application, you can use our configuration class.
It provides a bean of type Spanner, which starts the emulator before creating a client.
This configuration also stops the emulator when the Spring context is shut down.

In order to use it, you need to add the SpannerEmulatorSpringConfiguration.class to your configuration classes list in `@ContextConfiguration`.

[source,java]
----
import org.junit.runner.RunWith;

import org.springframework.cloud.gcp.test.SpannerEmulatorSpringConfiguration;

@RunWith(SpringRunner.class)
@ContextConfiguration(classes = {SpannerEmulatorSpringConfiguration.class, YourSpringConfiguration.class})
public class SpannerTemplateEmulatorTests {
		//your tests
}
----

==== JUnit 4 Class Rule
If you don't use spring in your tests, you can use the class rule.

NOTE: The rule does not work with SpringRunner!
See <<Spring Configuration>> section instead.

[source,java]
----
import org.springframework.cloud.gcp.test.SpannerEmulatorRule;

public class SpannerTests {
	@ClassRule
	public static SpannerEmulatorRule emulator = new SpannerEmulatorRule();

	//your tests
}
----



==== Utility class
If you prefer controlling the emulator manually, you can use SpannerEmulatorHelper.

[source,java]
----
	SpannerEmulatorHelper emulatorHelper = new SpannerEmulatorHelper();

	emulatorHelper.startEmulator();

	//your code

	emulatorHelper.shutdownEmulator();
----
