== Spring Cloud Sleuth

https://cloud.spring.io/spring-cloud-sleuth/[Spring Cloud Sleuth] is an instrumentation framework for Spring Boot
applications. It captures trace informations and can forward traces to services like Zipkin for storage and
analysis.

Google Cloud Platform provides its own managed distributed tracing service called
https://cloud.google.com/trace/[Stackdriver Trace]. Instead of running and maintaining your own Zipkin instance and
storage, you can use Stackdriver Trace to store traces, view trace details, generate latency distributions graphs,
and generate performance regression reports.

This Spring Cloud GCP starter can forward Spring Cloud Sleuth traces to Stackdriver Trace without an intermediary
Zipkin server.

Maven coordinates, using Spring Cloud GCP BOM:


[source,xml]
----
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-gcp-starter-trace</artifactId>
</dependency>
----

Gradle coordinates:

[source,subs="normal"]
----
dependencies {
    compile group: 'org.springframework.cloud', name: 'spring-cloud-gcp-starter-trace'
}
----

You must enable Stackdriver Trace API from the Google Cloud Console in order to capture traces. Navigate to the
https://console.cloud.google.com/apis/api/cloudtrace.googleapis.com/overview[Stackdriver Trace API] for your project
and make sure it’s enabled.

[NOTE]
====
If you are already using a Zipkin server capturing trace information from multiple platform/frameworks, you also use a
https://cloud.google.com/trace/docs/zipkin[Stackdriver Zipkin proxy] to forward those traces to Stackdriver Trace
without modifying existing applications.
====

=== Spring Boot Starter for Stackdriver Trace
Spring Boot Starter for Stackdriver Trace uses Spring Cloud Sleuth and auto-configures a
https://github.com/openzipkin/zipkin-reporter-java/blob/master/core/src/main/java/zipkin2/reporter/Reporter.java[Reporter]
that sends the Sleuth’s trace information to Stackdriver Trace.

This starter will send traces asynchronously using a buffered trace consumer that auto-flushes when its buffered trace
messages exceed its buffer size or have been buffered for longer than its scheduled delay.

There are several parameters you can use to tune the Stackdriver Trace adapter. All configurations are optional:

|===
| Name | Description | Optional | Default value
| `spring.cloud.gcp.trace.enabled` |
Auto-configure Spring Cloud Sleuth to send traces to Stackdriver Trace. | Yes | `true`
| `spring.cloud.gcp.trace.executor-threads` |
Number of threads to use by the underlying gRPC channel to send the trace request to Stackdriver. |
Yes | `4`
| `spring.cloud.gcp.trace.buffer-size-bytes` |
Buffer size in bytes. Traces will be flushed to Stackdriver when buffered trace messages exceed this
size. | Yes | 1% of Runtime.totalMemory()
| `spring.cloud.gcp.trace.scheduled-delay-seconds` |
Buffered trace messages will be flushed to Stackdriver when buffered longer than scheduled delays
(in seconds) even if the buffered message size didn't exceed the buffer size. | Yes | `10`
| `spring.cloud.gcp.trace.project-id` |
Overrides the project ID from the <<spring-cloud-gcp-core,Spring Cloud GCP Module>> | Yes |
| `spring.cloud.gcp.trace.credentials.location` |
Overrides the credentials location from the <<spring-cloud-gcp-core,Spring Cloud GCP Module>> |
Yes |
| `spring.cloud.gcp.trace.credentials.scopes` |
Overrides the credentials scopes from the <<spring-cloud-gcp-core,Spring Cloud GCP Module>> |
Yes |
|===

You can use core Spring Cloud Sleuth properties to control Sleuth’s sampling rate, etc.
Read https://cloud.spring.io/spring-cloud-sleuth/[Sleuth documentation] for more information on
Sleuth configurations.

For example, when you are testing to see the traces are going through, you can set the sampling rate
to 100%.

[source]
----
spring.sleuth.sampler.probability=1                     # Send 100% of the request traces to Stackdriver.
spring.sleuth.web.skipPattern=(^cleanup.*|.+favicon.*)  # Ignore some URL paths.
----

Spring Cloud GCP Trace does override some Sleuth configurations:

- Always uses 128-bit Trace IDs. This is required by Stackdriver Trace.
- Does not use Span joins. Span joins will share the span ID between the client and server Spans.
  Stackdriver requires that every Span ID within a Trace to be unique, so Span joins are not supported.
- Uses `StackdriverHttpClientParser` and `StackdriverHttpServerParser` by default to populate Stackdriver
  related fields.

=== Stackdriver Logging Support

Maven coordinates, using Spring Cloud GCP BOM:

[source,xml]
----
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-gcp-logging</artifactId>
</dependency>
----

Gradle coordinates:

[source]
----
dependencies {
    compile group: 'org.springframework.cloud', name: 'spring-cloud-gcp-logging'
}
----

https://cloud.google.com/logging/[Stackdriver Logging] is the managed logging service provided by Google Cloud
Platform.

This module provides support for associating a web request trace ID with the corresponding log entries.
This allows grouping of log messages by request.

NOTE: Due to the way logging is set up, the GCP project ID and credentials defined in
`application.properties` are ignored.
Instead, you should set the `GOOGLE_CLOUD_PROJECT` and `GOOGLE_APPLICATION_CREDENTIALS` environment
variables to the project ID and credentials private key location, respectively.

`TraceIdLoggingWebMvcInterceptor` extracts the request trace ID from an HTTP request using a
`TraceIdExtractor` and stores it in a thread-local of the https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-logging/src/main/java/com/google/cloud/logging/TraceLoggingEnhancer.java[`TraceLoggingEnhancer`]
which can then be used in a logging appender to add the trace ID metadata to log messages.

There are implementations provided for `TraceIdExtractor`:

[options="header",]
|=======================================================================
| Extractor | Description
| `XCloudTraceIdExtractor` | Checks the `X-Cloud-Trace-Context` HTTP header that is automatically added to HTTP requests sent to applications hosted on GCP services such as App Engine and GKE
| `ZipkinTraceIdExtractor` | Checks the `X-B3-TraceId` header
| `CompositeTraceIdExtractor` | Instantiated with a list of other `TraceIdExtractor`, and provides the first trace ID found using these extractors in the given order
|=======================================================================

`LoggingWebMvcConfigurer` configuration class is also provided to help register the `TraceIdLoggingWebMvcInterceptor`
in Spring MVC applications.

Currently, https://github.com/GoogleCloudPlatform/google-cloud-java/tree/master/google-cloud-logging#add-a-stackdriver-logging-handler-to-a-logger[Java Util Logging (JUL)]
and https://github.com/GoogleCloudPlatform/google-cloud-java/tree/master/google-cloud-contrib/google-cloud-logging-logback[Logback] are supported.

==== Logback Support

There are 2 possibilities to log to Stackdriver via this library with Logback:

===== Log via API

For Logback, a `org/springframework/cloud/gcp/logging/logback-appender.xml` file is made available for import to make it
easier to configure the Logback appender.

Your configuration may then look something like this:
[source, xml]
----
<configuration>
  <include resource="org/springframework/cloud/gcp/logging/logback-appender.xml" />

  <root level="INFO">
    <appender-ref ref="STACKDRIVER" />
  </root>
</configuration>
----

`STACKDRIVER_LOG_NAME` and `STACKDRIVER_LOG_FLUSH_LEVEL` environment variables can be used to customize the
`STACKDRIVER` appender.

Also see the link:../spring-cloud-gcp-starters/spring-cloud-gcp-starter-logging[spring-cloud-gcp-starter-logging] module.

===== Log via Console

If you run your Spring Boot application in a Kubernetes cluster in the Google Cloud (GKE) or on App Engine flexible
environment, you can log JSON directly from the console by including
`org/springframework/cloud/gcp/logging/logback-json-appender.xml`. The traceId will be set
correctly.

You need the additional dependency:

[source, xml]
----
<dependency>
  <groupId>ch.qos.logback.contrib</groupId>
  <artifactId>logback-json-classic</artifactId>
  <version>0.1.5</version>
</dependency>
----

Your Logback configuration may then look something like this:

[source, xml]
----
<configuration>
  <property name="projectId" value="test-project"/>
  <include resource="org/springframework/cloud/gcp/logging/logback-json-appender.xml" />

  <root level="INFO">
    <appender-ref ref="CONSOLE_JSON"/>
  </root>
</configuration>
----

If you want to have more control over the log output, you can also configure the `ConsoleAppender` yourself.
The following properties are available:

[options="header",]
|=======================================================================
| Property | Default Value | Description
| `projectId` |  | Only required for logging the correct traceId: `projects/[PROJECT-ID]/traces/[TRACE-ID]`. If `projectId` is not set, the logged `traceId` will match the one provided by `spring-cloud-gpc-trace`
| `includeTraceId` | `true` | Should the `traceId` be included
| `includeSpanId` | `true` | Should the `spanId` be included
| `includeLevel` | `true` | Should the severity be included
| `includeThreadName` | `true` | Should the thread name be included
| `includeMDC` | `true` | Should all MDC properties be included. The MDC properties `X-B3-TraceId`, `X-B3-SpanId` and `X-Span-Export` provided by Spring Sleuth will get excluded as they get handled separately
| `includeLoggerName` | `true` | Should the name of the logger be included
| `includeFormattedMessage` | `true` | Should the formatted log message be included.
| `includeExceptionInMessage` | `true` | Should the stacktrace be appended to the formatted log message. This setting is only evaluated if `includeFormattedMessage` is `true`
| `includeContextName` | `true` | Should the logging context be included
| `includeMessage` | `false` | Should the log message with blank placeholders be included
| `includeException` | `false` | Should the stacktrace be included as a own field
|=======================================================================

This is an example of such an Logback configuration:

[source, xml]
----
<configuration >
  <property name="projectId" value="${projectId:-${GOOGLE_CLOUD_PROJECT}}"/>

  <appender name="CONSOLE_JSON" class="ch.qos.logback.core.ConsoleAppender">
    <encoder class="ch.qos.logback.core.encoder.LayoutWrappingEncoder">
      <layout class="org.springframework.cloud.gcp.logging.StackdriverJsonLayout">
        <projectId>${projectId}</projectId>

        <!--<includeTraceId>true</includeTraceId>-->
        <!--<includeSpanId>true</includeSpanId>-->
        <!--<includeLevel>true</includeLevel>-->
        <!--<includeThreadName>true</includeThreadName>-->
        <!--<includeMDC>true</includeMDC>-->
        <!--<includeLoggerName>true</includeLoggerName>-->
        <!--<includeFormattedMessage>true</includeFormattedMessage>-->
        <!--<includeExceptionInMessage>true</includeExceptionInMessage>-->
        <!--<includeContextName>true</includeContextName>-->
        <!--<includeMessage>false</includeMessage>-->
        <!--<includeException>false</includeException>-->
      </layout>
    </encoder>
  </appender>
</configuration >
----
