= Google Cloud Storage Spring Boot Starter

Maven coordinates, using Spring Cloud GCP BOM:

[source,xml]
----
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-gcp-starter-storage</artifactId>
</dependency>
----

Gradle coordinates:

[source]
----
dependencies {
    compile group: 'org.springframework.cloud', name: 'spring-cloud-gcp-starter-storage', version: '1.0.0.BUILD-SNAPSHOT'
}
----


This starter provides the underpinnings of the Spring Cloud GCP Storage. It doesn't provide any
bean to be used by an end-user.

There is an optional property, `spring.cloud.gcp.storage.credentials-location`. Its value is the
filesystem path for a credentials file, in case Storage is served from a different GCP project ID
than the one configured in the link:../spring-cloud-gcp-starter-core/README.adoc[Core Starter].

The optional property `spring.cloud.gcp.storage.auto-create-files` causes a new file to be created
with a given URI if an output stream was requested from that URI but there was no file at that URI.
If `true`, the default setting, then new files are automatically created.