= Google Cloud Storage Spring Boot Starter

Maven coordinates, using Spring Cloud GCP BOM:

[source,xml]
----
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-gcp-starter-storage</artifactId>
</dependency>
----

Gradle coordinates:

[source]
----
dependencies {
    compile group: 'org.springframework.cloud', name: 'spring-cloud-gcp-starter-storage'
}
----


This starter provides the underpinnings of the Spring Cloud GCP Storage. It doesn't provide any
bean to be used by an end-user.

[options="header",]
|=======================================================================
| Setting | Required | Default Value | Meaning
| `spring.cloud.gcp.storage.auto-create-files` | No | `true` | If `true`, new file will be created
at given URL if none exists when getting output stream
| `spring.cloud.gcp.storage.credentials.location` | No | Location of the credentials for the
Storage service, if different from those in the
link:../spring-cloud-gcp-starter/README.adoc[GCP Starter] | the filesystem path for a
credentials private key file
| `spring.cloud.gcp.storage.credentials.scopes` | No | List of scopes for this service-specific
credentials |
|=======================================================================
