= Spring Cloud GCP SQL Starter Example

This code sample demonstrates how to connect to a Google Cloud SQL instance using the
link:../../spring-cloud-gcp-starters/spring-cloud-gcp-starter-sql/README.adoc[Spring Cloud GCP SQL
Starter].

We will create an instance, a database within the instance, populate the database and then query it.

= Setup & Configuration

1. Follow https://cloud.google.com/sql/docs/mysql/quickstart[these instructions] to set up a Google
Cloud Project with billing enabled and a Google Cloud SQL instance.

2. Still within the Google Cloud Console, create a new database in the instance from the
"Databases" section.

3. Open the link:src/main/resources/application.properties[application.properties] file and replace
*[database-name]* by the name of the database you created on 2 and *[instance-connection-name]* by
the instance connection name of the instance you created on 1.
+
If you set a root password, you should also add a `spring.cloud.gcp.sql.password` property with the
password as the value.

4. https://cloud.google.com/sdk/gcloud/reference/auth/login[Authenticate in the Cloud SDK] or add
a `spring.cloud.gcp.sql.credentials-location` property with the path on your local file system to
a credentials file, prepended with `file:`.

5. Run the `SqlApplication` Spring Boot app. The database will be populated based on the
link:src/main/resources/schema.sql[schema.sql] and link:src/main/resources/data.sql[data.sql] files.

6. Navigate to http://localhost:8080/getTuples on your browser to print the contents of the table
created in 5.
