= Spring Cloud GCP Cloud Datastore Bookshelf Example

This code sample demonstrates how to read and write POJOs from Google Cloud Datastore using the SpringData Cloud Datastore module link:../../spring-cloud-gcp-starters/spring-cloud-gcp-starter-data-datastore[Spring Cloud GCP Cloud Datastore Starter].

== Running the example

. Create a new Cloud Datastore database in your GCP project if this has not already been done to allow Cloud Datastore to create and store entities.

. https://cloud.google.com/sdk/gcloud/reference/auth/application-default/login[If you are authenticated in the Cloud SDK], your credentials will be automatically found by the Spring Boot Starter for Google Cloud Datastore.
+
Alternatively, https://console.cloud.google.com/iam-admin/serviceaccounts[create a service account from the Google Cloud Console] and download its private key.
+
Then, uncomment the `spring.cloud.gcp.datastore.credentials.location` property in the link:src/main/resources/application.properties[application.properties] file and fill its value with the path to your service account private key on your local file system, prepended with `file:`.

. Run the `DatastoreBookshelfExample` Spring Boot console app:
+
`mvn spring-boot:run`

. Use shell to create, find and remove books.
Available commands:
+
----
save-book <title> <author> <year>
find-all-books
find-by-author <author>
find-by-year-greater-than <year>
find-by-author-year <author> <year>
remove-all-books
----
+
Example:
+
----
shell:>save-book "The Moon Is a Harsh Mistress" "Robert A. Heinlein" 1966
shell:>save-book "Stranger in a Strange Land" "Robert A. Heinlein" 1961
shell:>save-book "The Crack in Space" "Philip K. Dick" 1966
shell:>save-book "Ubik" "Philip K. Dick" 1969

shell:>find-by-year-greater-than 1967
[Book{id=5734055144325120, title='Ubik', author='Philip K. Dick', year=1969}]

shell:>find-by-author-year "Robert A. Heinlein" 1966
[Book{id=5652161459388416, title='The Moon Is a Harsh Mistress', author='Robert A. Heinlein', year=1966}]
----

. To clean up the database run the following command in the application shell:
+
`shell:>remove-all-books`

. Use `Ctrl+C` `Ctrl+C` to exit
