= Spring Cloud GCP Cloud Spanner Starter Example

This code sample demonstrates how to set up a gRPC service reading from Google Cloud Spanner using the Spring
Data Cloud Spanner module link:../../spring-cloud-gcp-starters/spring-cloud-gcp-starter-data-spanner[Spring Cloud GCP Cloud Spanner Starter].

== Running the example


. Create a new Cloud Spanner instance named "spring-demo".
The example application will create the database and tables if they do not already exist.
[start=2]
. https://cloud.google.com/sdk/gcloud/reference/auth/application-default/login[If you are authenticated in the Cloud SDK], your credentials will be automatically found by the Spring
Boot Starter for Google Cloud Spanner.
+
Alternatively, https://console.cloud.google.com/iam-admin/serviceaccounts[create a service account from the Google Cloud Console] and download its private key.
+
Then, uncomment the `spring.cloud.gcp.spanner.credentials.location` property in the link:src/main/resources/application.properties[application.properties] file and fill its value with the path to your service account private key on your local file system, prepended with `file:`.

. Run the sample app (it will generate some sample `Trade` objects filled with some demo data and persists them to the Cloud Spanner table created earlier).
These POJOs are then retrieved and their contents are printed in the browser.

. To run the SpannerRepositoryExample:

----
mvn spring-boot:run
----

The sample application provides an RPC endpoint `com.example.service.TradeService.listTrades` and an HTTP endpoint `http://localhost:8080/trades`.
The HTTP endpoint will call the RPC endpoint that will, in turn, retrieve data from Spanner and propagate it back.
