= Spring Cloud GCP Config Client Starter Example

This sample application demonstrates using the
link:../../spring-cloud-gcp-starters/spring-cloud-gcp-starter-config[Spring Cloud GCP Config Client Starter] in your code.

== Setup & Configuration
1. Follow link:../../spring-cloud-gcp-starters/spring-cloud-gcp-starter-config[these setup instructions].
2.  Create a configuration using the
https://cloud.google.com/sdk/[Google Cloud SDK].
+
....
gcloud beta runtime-config configs create myapp_prod
....
+
Then set the variables:
+
....
  gcloud beta runtime-config configs variables set \
queue_size 25 \
--config-name myapp_prod
  gcloud beta runtime-config configs variables set \
feature_x_enabled true \
--config-name myapp_prod
....

3.  Update link:src/main/resources/bootstrap.properties[]:
+
....
spring.cloud.gcp.config.enabled=true #optional, default = true
spring.cloud.gcp.config.name=myapp
spring.cloud.gcp.config.profile=prod #default profile = default
....
4.  Add Spring style configuration variables, see
link:src/main/java/com/example/SampleConfig.java[SampleConfig.java].
+
....
@Value("${queue_size}")
private int queueSize;

@Value("${feature_x_enabled}")
private boolean isFeatureXEnabled;
....
5.  Update a property with `gcloud`:
+
....
  gcloud beta runtime-config configs variables set \
     queue_size 200 \
     --config-name myapp_prod
....
6.  Send a POST request to the `/refresh` endpoint:
+
....
  curl -XPOST http://myapp.host.com/refresh
....
