= Spring Cloud GCP Metrics Starter Example

This sample application demonstrates using the
link:../../spring-cloud-gcp-starters/spring-cloud-gcp-starter-metrics[Spring Cloud GCP Metrics
Starter] to store metrics, with the Google Stackdriver Monitoring API.

== Setup & Configuration
1. Create a Google Cloud Platform Project
2. Have the https://cloud.google.com/sdk/[Google Cloud SDK] installed, initialized and logged in with https://developers.google.com/identity/protocols/application-default-credentials[application default credentials].
3. Check that the https://console.cloud.google.com/apis/library/monitoring.googleapis.com/[Stackdriver Monitoring API is enabled].

== Running the Example
Run the sample application from Maven:

----
$ mvn spring-boot:run
----

Then, issue a request to `localhost:8080/` endpoint and verify that a label appears in Stackdriver:

----
$ curl localhost:8080/
----

To see the metrics, navigate to the https://console.cloud.google.com/monitoring/metrics-explorer[Monitoring section of the Cloud Console].
Select the `custom/ping` metric to see the tracked metric.

=== Running on Google Cloud Platform

Deploy to App Engine:

----
$ mvn clean package appengine:deploy -Dapp.deploy.projectId=$PROJECT_ID -Dapp.deploy.version=$VERSION
----
