= Spring Cloud GCP Metrics Starter Example

This sample application demonstrates using the
link:../../spring-cloud-gcp-starters/spring-cloud-gcp-starter-metrics[Spring Cloud GCP Metrics
Starter] to store metrics, with the Google Stackdriver Monitoring API.

== Setup & Configuration

image:http://gstatic.com/cloudssh/images/open-btn.svg[link=https://ssh.cloud.google.com/cloudshell/editor?cloudshell_git_repo=https%3A%2F%2Fgithub.com%2FGoogleCloudPlatform%2Fspring-cloud-gcp&cloudshell_open_in_editor=spring-cloud-gcp-samples/spring-cloud-gcp-metrics-sample/README.adoc]

1. Create a Google Cloud Platform Project
2. Have the https://cloud.google.com/sdk/[Google Cloud SDK] installed, initialized and logged in with https://developers.google.com/identity/protocols/application-default-credentials[application default credentials].
3. Check that the https://console.cloud.google.com/apis/library/monitoring.googleapis.com/[Stackdriver Monitoring API is enabled].
4. Run `$ mvn clean install` from the root directory of the project.

== Running the Example
Run the following command in the same directory as this sample (spring-cloud-gcp-samples/spring-cloud-gcp-metrics-sample):

----
$ mvn spring-boot:run
----

Then, issue a request to `localhost:8080/{custom metric name}` endpoint and verify that the metric appears in Stackdriver:

----
$ curl localhost:8080/my_ping_counter
----

Metrics are reported to Stackdriver every 60 seconds.
So, wait a minute for the custom metric to be reported.
To see the metrics, navigate to the https://console.cloud.google.com/monitoring/metrics-explorer[Monitoring section of the Cloud Console].
Select the `custom/my_ping_counter` metric to see the tracked metric.

=== Running on Google Cloud Platform

Deploy to App Engine:

----
$ mvn clean package appengine:deploy -Dapp.deploy.projectId=$PROJECT_ID -Dapp.deploy.version=$VERSION
----
