= Spring Data JPA with Spring Cloud GCP SQL Sample

This sample application demonstrates how to use
https://projects.spring.io/spring-data-jpa/[Spring Data JPA] with the
link:../../spring-cloud-gcp-starters/spring-cloud-gcp-starter-sql[Spring Cloud GCP SQL Starter].

We will create an instance, a database within the instance, populate the database and then query it.

== Setup

1. Follow https://cloud.google.com/sql/docs/mysql/quickstart[these instructions] to set up a Google
Cloud Project with billing enabled.

2. Create a Google Cloud SQL instance from the
https://console.cloud.google.com/sql/instances[Google Cloud Console Cloud SQL page].

3. Still within the Google Cloud Console SQL page, create a new database in the instance from the
"Databases" section. If you decided to set a root password for your instance footnoteref:[note, Google Cloud SQL allows for creating MySQL instances without a password, while still remaining safe, as the connection is using Cloud SDK authentication and encrypted communication: see docs on https://cloud.google.com/sql/docs/mysql/sql-proxy[Cloud SQL proxy] and https://cloud.google.com/sql/docs/mysql/connect-external-app#java[the java socketFactory], which is used in spring-cloud-gcp to create the connection!], then don't forget to take note of your root password, as you will need it in the next step!

4. Open the link:src/main/resources/application.properties[application.properties] file and replace
*[database-name]* with the name of the database you created in step 3 and
*[instance-connection-name]* with the instance connection name of the instance you created in
step 1.
+
If you set a root password, add the `spring.datasource.password` property with the root password as the value.

5. https://cloud.google.com/sdk/gcloud/reference/auth/login[If
you are authenticated in the Cloud SDK], your project ID and credentials will be automatically found
by the Spring Boot Starter for Google Cloud SQL.
+
Alternatively, uncomment the `spring.cloud.gcp.sql.project-id` and
`spring.cloud.gcp.sql.credentials.location` properties in the
link:src/main/resources/application.properties file and fill the values with your project ID and
the path to your service account credentials on your local file system, prepended with `file:`.

== Running the application

This application uses the Spring Cloud GCP SQL starter to configure a `JdbcTemplate` object, which
the Spring Data JPA starter uses as an input.

This application is runnable by executing the following command from the same directory where the
`pom.xml` file is located:

`$ mvn spring-boot:run`

It writes a few house tuples to the database and then reads and prints each house address from the
database.
